// frontend/src/pages/clients/ClientFormModal.tsx
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Button,
  Col,
  Form,
  Input,
  InputNumber,
  Modal,
  Row,
  Select,
  Space,
  Switch,
  Tag,
  message,
} from 'antd';
import dayjs from 'dayjs';
import type { Dayjs } from 'dayjs';

import { HttpUtil, RandomUtil } from '@/utils';
import DateTimePicker from '@/components/DateTimePicker';
import { TLS_FLOW_CONTROL } from '@/models/inbound';
import type { ClientRecord, InboundOption } from '@/hooks/useClients';
import './ClientFormModal.css';

const FLOW_OPTIONS = Object.values(TLS_FLOW_CONTROL);

const MULTI_CLIENT_PROTOCOLS = new Set([
  'shadowsocks', 'vless', 'vmess', 'trojan', 'hysteria', 'hysteria2',
]);

interface ApiMsg<T = unknown> {
  success?: boolean;
  obj?: T;
}

type Mode = 'add' | 'edit';

interface SaveMetaEdit {
  isEdit: true;
  email: string;
  attach: number[];
  detach: number[];
}

interface SaveMetaCreate {
  isEdit: false;
}

interface SaveCreatePayload {
  client: Record<string, unknown>;
  inboundIds: number[];
}

interface ClientFormModalProps {
  open: boolean;
  mode: Mode;
  client: ClientRecord | null;
  inbounds: InboundOption[];
  attachedIds?: number[];
  ipLimitEnable?: boolean;
  tgBotEnable?: boolean;
  save: (
    payload: Record<string, unknown> | SaveCreatePayload,
    meta: SaveMetaEdit | SaveMetaCreate,
  ) => Promise<ApiMsg | null>;
  onOpenChange: (open: boolean) => void;
}

interface SubscriptionOption {
  id: number;
  subId: string;
  remark: string;
  enable: boolean;
  expiryTime: number;
}

interface FormState {
  email: string;
  subId: string;
  uuid: string;
  password: string;
  auth: string;
  flow: string;
  reverseTag: string;
  totalGB: number;
  expiryDate: Dayjs | null;
  delayedStart: boolean;
  delayedDays: number;
  limitIp: number;
  tgId: number;
  comment: string;
  enable: boolean;
  inboundIds: number[];
  subscriptionIds: number[];
}

function emptyForm(): FormState {
  return {
    email: '',
    subId: '',
    uuid: '',
    password: '',
    auth: '',
    flow: TLS_FLOW_CONTROL.VISION,
    reverseTag: '',
    totalGB: 0,
    expiryDate: null,
    delayedStart: false,
    delayedDays: 0,
    limitIp: 0,
    tgId: 0,
    comment: '',
    enable: true,
    inboundIds: [],
    subscriptionIds: [],
  };
}

function bytesToGB(bytes: number): number {
  if (!bytes || bytes <= 0) return 0;
  return Math.round((bytes / (1024 * 1024 * 1024)) * 100) / 100;
}

function gbToBytes(gb: number): number {
  if (!gb || gb <= 0) return 0;
  return Math.round(gb * 1024 * 1024 * 1024);
}

export default function ClientFormModal({
  open,
  mode,
  client,
  inbounds,
  attachedIds = [],
  ipLimitEnable = false,
  tgBotEnable = false,
  save,
  onOpenChange,
}: ClientFormModalProps) {
  const { t } = useTranslation();
  const [messageApi, messageContextHolder] = message.useMessage();
  const isEdit = mode === 'edit';

  const [form, setForm] = useState<FormState>(emptyForm);
  const [submitting, setSubmitting] = useState(false);
  const [clientIps, setClientIps] = useState<string[]>([]);
  const [ipsLoading, setIpsLoading] = useState(false);
  const [ipsClearing, setIpsClearing] = useState(false);
  const [allSubscriptions, setAllSubscriptions] = useState<SubscriptionOption[]>([]);

  function update<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  useEffect(() => {
    if (!open) return;

    // Fetch subscriptions for the dropdown
    (async () => {
      const msg = await HttpUtil.get('/panel/api/subscription/list') as ApiMsg<SubscriptionOption[]>;
      if (msg?.success && Array.isArray(msg.obj)) setAllSubscriptions(msg.obj);
    })();

    if (isEdit && client) {
      const et = Number(client.expiryTime) || 0;
      const next: FormState = {
        ...emptyForm(),
        email: client.email || '',
        subId: client.subId || '',
        uuid: client.uuid || '',
        password: client.password || '',
        auth: client.auth || '',
        flow: client.flow || '',
        reverseTag: client.reverse?.tag || '',
        totalGB: bytesToGB(client.totalGB || 0),
        limitIp: client.limitIp || 0,
        tgId: Number(client.tgId) || 0,
        comment: client.comment || '',
        enable: !!client.enable,
        inboundIds: Array.isArray(attachedIds) ? [...attachedIds] : [],
        subscriptionIds: [],
      };
      if (et < 0) {
        next.delayedStart = true;
        next.delayedDays = Math.round(et / -86400000);
        next.expiryDate = null;
      } else {
        next.delayedStart = false;
        next.delayedDays = 0;
        next.expiryDate = et > 0 ? dayjs(et) : null;
      }
      setForm(next);
      void loadIps();
    } else {
      setForm({
        ...emptyForm(),
        email: RandomUtil.randomLowerAndNum(9),
        uuid: RandomUtil.randomUUID(),
        subId: RandomUtil.randomLowerAndNum(16),
        password: RandomUtil.randomLowerAndNum(16),
        auth: RandomUtil.randomLowerAndNum(16),
      });
    }
     
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, isEdit]);

  const flowCapableIds = useMemo(() => {
    const ids = new Set<number>();
    for (const row of inbounds || []) {
      if (row?.tlsFlowCapable) ids.add(row.id);
    }
    return ids;
  }, [inbounds]);

  const vlessLikeIds = useMemo(() => {
    const ids = new Set<number>();
    for (const row of inbounds || []) {
      if (row && row.protocol === 'vless') ids.add(row.id);
    }
    return ids;
  }, [inbounds]);

  const showFlow = useMemo(
    () => (form.inboundIds || []).some((id) => flowCapableIds.has(id)),
    [form.inboundIds, flowCapableIds],
  );

  const showReverseTag = useMemo(
    () => (form.inboundIds || []).some((id) => vlessLikeIds.has(id)),
    [form.inboundIds, vlessLikeIds],
  );

  useEffect(() => {
    if (!showFlow && form.flow) {
       
      update('flow', '');
    }
  }, [showFlow, form.flow]);

  useEffect(() => {
    if (!showReverseTag && form.reverseTag) {

      update('reverseTag', '');
    }
  }, [showReverseTag, form.reverseTag]);

  // When editing, load which subscriptions already include this client
  useEffect(() => {
    if (!open || !isEdit || !client?.email || allSubscriptions.length === 0) return;
    // subscription list already fetched — find which ones include this email
    // We need to query backend since we only have the subscription list without clientEmails
    (async () => {
      const msg = await HttpUtil.get(
        `/panel/api/inbounds/checkClientSubscriptions?email=${encodeURIComponent(client.email)}`,
      ) as ApiMsg<{ affected: { id: number }[]; toBeDeleted: { id: number }[] }>;
      if (msg?.success && msg.obj) {
        const ids = new Set<number>();
        for (const s of (msg.obj.affected || [])) ids.add(s.id);
        for (const s of (msg.obj.toBeDeleted || [])) ids.add(s.id);
        update('subscriptionIds', [...ids]);
      }
    })();
  }, [open, isEdit, client?.email, allSubscriptions.length]);

  const NOW = useMemo(() => Date.now(), []);
  const inboundOptions = useMemo(
    () => (inbounds || [])
      .filter((ib) => MULTI_CLIENT_PROTOCOLS.has(ib.protocol || ''))
      .map((ib) => {
        let tag = '';
        const used = Number(ib.up || 0) + Number(ib.down || 0);
        if (!ib.enable) tag = t('disabled');
        else if (ib.expiryTime && ib.expiryTime > 0 && NOW > ib.expiryTime) tag = t('expired');
        else if (Number(ib.total || 0) > 0 && used >= Number(ib.total || 0)) tag = t('depleted');
        const label = `${ib.remark || `#${ib.id}`} · ${ib.protocol}:${ib.port}${tag ? ` (${tag})` : ''}`;
        return {
          label,
          value: ib.id,
          title: `${ib.remark || ''} (${ib.protocol}:${ib.port})`,
        };
      }),
    [inbounds, t, NOW],
  );

  const subscriptionOptions = useMemo(
    () => (allSubscriptions || []).map((s) => {
      let tag = '';
      if (!s.enable) tag = t('disabled');
      else if (s.expiryTime && s.expiryTime > 0 && NOW > s.expiryTime) tag = t('expired');
      const label = `${s.remark || s.subId} (${s.subId})${tag ? ` (${tag})` : ''}`;
      return { label, value: s.id };
    }),
    [allSubscriptions, t, NOW],
  );

  async function loadIps() {
    if (!isEdit || !client?.email) return;
    setIpsLoading(true);
    try {
      const msg = await HttpUtil.post(`/panel/api/clients/ips/${encodeURIComponent(client.email)}`) as ApiMsg<unknown[]>;
      if (!msg?.success) { setClientIps([]); return; }
      const arr = Array.isArray(msg.obj) ? msg.obj : [];
      setClientIps(arr.filter((x): x is string => typeof x === 'string' && x.length > 0));
    } finally {
      setIpsLoading(false);
    }
  }

  async function clearIps() {
    if (!isEdit || !client?.email) return;
    setIpsClearing(true);
    try {
      const msg = await HttpUtil.post(`/panel/api/clients/clearIps/${encodeURIComponent(client.email)}`) as ApiMsg;
      if (msg?.success) setClientIps([]);
    } finally {
      setIpsClearing(false);
    }
  }

  function close() {
    onOpenChange(false);
  }

  async function onSubmit() {
    if (!form.email || form.email.trim() === '') {
      messageApi.error(`${t('pages.clients.email')} *`);
      return;
    }
    if (!isEdit && (!form.inboundIds || form.inboundIds.length === 0)) {
      messageApi.error(t('pages.clients.selectInbound'));
      return;
    }
    const expiryTime = form.delayedStart
      ? -86400000 * (Number(form.delayedDays) || 0)
      : (form.expiryDate ? form.expiryDate.valueOf() : 0);
    const clientPayload: Record<string, unknown> = {
      email: form.email.trim(),
      subId: form.subId,
      id: form.uuid,
      password: form.password,
      auth: form.auth,
      flow: showFlow ? (form.flow || '') : '',
      totalGB: gbToBytes(form.totalGB),
      expiryTime,
      limitIp: Number(form.limitIp) || 0,
      tgId: Number(form.tgId) || 0,
      comment: form.comment,
      enable: !!form.enable,
    };
    const reverseTag = showReverseTag ? (form.reverseTag || '').trim() : '';
    if (reverseTag) {
      clientPayload.reverse = { tag: reverseTag };
    }

    setSubmitting(true);
    try {
      let msg;
      if (isEdit && client) {
        const original = new Set(attachedIds || []);
        const next = new Set(form.inboundIds || []);
        const toAttach = [...next].filter((id) => !original.has(id));
        const toDetach = [...original].filter((id) => !next.has(id));
        (clientPayload as Record<string, unknown>).subscriptionIds = form.subscriptionIds || [];
        msg = await save(clientPayload, {
          isEdit: true,
          email: client.email,
          attach: toAttach,
          detach: toDetach,
        });
      } else {
        msg = await save(
          { client: clientPayload, inboundIds: form.inboundIds, subscriptionIds: form.subscriptionIds || [] },
          { isEdit: false },
        );
      }
      if (msg?.success) close();
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <>
      {messageContextHolder}
      <Modal
        open={open}
        title={isEdit ? t('pages.clients.editTitle') : t('pages.clients.addTitle')}
        destroyOnHidden
      okText={isEdit ? t('save') : t('create')}
      cancelText={t('cancel')}
      okButtonProps={{ loading: submitting }}
      width={720}
      onOk={onSubmit}
      onCancel={close}
    >
      <Form layout="vertical">
        <Row gutter={16}>
          <Col xs={24} md={12}>
            <Form.Item label={t('pages.clients.email')} required>
              <Space.Compact style={{ display: 'flex' }}>
                <Input
                  value={form.email}
                  placeholder={t('pages.clients.email')}
                  style={{ flex: 1 }}
                  onChange={(e) => update('email', e.target.value)}
                />
                <Button onClick={() => update('email', RandomUtil.randomLowerAndNum(12))}>↻</Button>
              </Space.Compact>
            </Form.Item>
          </Col>
          <Col xs={24} md={12}>
            <Form.Item label={t('pages.clients.subId')}>
              <Space.Compact style={{ display: 'flex' }}>
                <Input value={form.subId} style={{ flex: 1 }} onChange={(e) => update('subId', e.target.value)} />
                <Button onClick={() => update('subId', RandomUtil.randomLowerAndNum(16))}>↻</Button>
              </Space.Compact>
            </Form.Item>
          </Col>
        </Row>

        <Row gutter={16}>
          <Col xs={24} md={12}>
            <Form.Item label={t('pages.clients.hysteriaAuth')}>
              <Space.Compact style={{ display: 'flex' }}>
                <Input value={form.auth} style={{ flex: 1 }} onChange={(e) => update('auth', e.target.value)} />
                <Button onClick={() => update('auth', RandomUtil.randomLowerAndNum(16))}>↻</Button>
              </Space.Compact>
            </Form.Item>
          </Col>
          <Col xs={24} md={12}>
            <Form.Item label={t('pages.clients.password')}>
              <Space.Compact style={{ display: 'flex' }}>
                <Input value={form.password} style={{ flex: 1 }} onChange={(e) => update('password', e.target.value)} />
                <Button onClick={() => update('password', RandomUtil.randomLowerAndNum(16))}>↻</Button>
              </Space.Compact>
            </Form.Item>
          </Col>
        </Row>

        <Row gutter={16}>
          <Col xs={24} md={12}>
            <Form.Item label={t('pages.clients.uuid')}>
              <Space.Compact style={{ display: 'flex' }}>
                <Input value={form.uuid} style={{ flex: 1 }} onChange={(e) => update('uuid', e.target.value)} />
                <Button onClick={() => update('uuid', RandomUtil.randomUUID())}>↻</Button>
              </Space.Compact>
            </Form.Item>
          </Col>
          <Col xs={24} md={ipLimitEnable ? 8 : 12}>
            <Form.Item label={t('pages.clients.totalGB')}>
              <InputNumber value={form.totalGB} min={0} step={1} style={{ width: '100%' }}
                onChange={(v) => update('totalGB', Number(v) || 0)} />
            </Form.Item>
          </Col>
          {ipLimitEnable && (
            <Col xs={24} md={4}>
              <Form.Item label={t('pages.clients.limitIp')}>
                <InputNumber value={form.limitIp} min={0} style={{ width: '100%' }}
                  onChange={(v) => update('limitIp', Number(v) || 0)} />
              </Form.Item>
            </Col>
          )}
        </Row>

        <Row gutter={16}>
          <Col xs={24} md={12}>
            {form.delayedStart ? (
              <Form.Item label={t('pages.clients.expireDays')}>
                <InputNumber value={form.delayedDays} min={0} style={{ width: '100%' }}
                  onChange={(v) => update('delayedDays', Number(v) || 0)} />
              </Form.Item>
            ) : (
              <Form.Item label={t('pages.clients.expiryTime')}>
                <DateTimePicker
                  value={form.expiryDate}
                  onChange={(d) => update('expiryDate', d || null)}
                />
              </Form.Item>
            )}
          </Col>
          <Col xs={24} md={12}>
            <Form.Item label={t('pages.clients.delayedStart')}>
              <Switch
                checked={form.delayedStart}
                onChange={(v) => {
                  update('delayedStart', v);
                  if (v) update('expiryDate', null);
                  else update('delayedDays', 0);
                }}
              />
            </Form.Item>
          </Col>
        </Row>

        {(showFlow || showReverseTag) && (
          <Row gutter={16}>
            {showFlow && (
              <Col xs={24} md={12}>
                <Form.Item label={t('pages.clients.flow')}>
                  <Select
                    value={form.flow}
                    onChange={(v) => update('flow', v)}
                    options={[
                      { value: '', label: t('none') },
                      ...FLOW_OPTIONS.map((k) => ({ value: k, label: k })),
                    ]}
                  />
                </Form.Item>
              </Col>
            )}
            {showReverseTag && (
              <Col xs={24} md={12}>
                <Form.Item label={t('pages.clients.reverseTag')}>
                  <Input value={form.reverseTag} placeholder={t('pages.clients.reverseTagPlaceholder')}
                    onChange={(e) => update('reverseTag', e.target.value)} />
                </Form.Item>
              </Col>
            )}
          </Row>
        )}

        <Row gutter={16}>
          {tgBotEnable && (
            <Col xs={24} md={12}>
              <Form.Item label={t('pages.clients.telegramId')}>
                <InputNumber value={form.tgId} min={0} controls={false}
                  placeholder={t('pages.clients.telegramIdPlaceholder')} style={{ width: '100%' }}
                  onChange={(v) => update('tgId', Number(v) || 0)} />
              </Form.Item>
            </Col>
          )}
          <Col xs={24} md={tgBotEnable ? 12 : 24}>
            <Form.Item label={t('pages.clients.comment')}>
              <Input value={form.comment} onChange={(e) => update('comment', e.target.value)} />
            </Form.Item>
          </Col>
        </Row>

        <Form.Item label={t('pages.clients.attachedInbounds')} required={!isEdit}>
          <Select
            mode="multiple"
            value={form.inboundIds}
            onChange={(v) => update('inboundIds', v)}
            options={inboundOptions}
            showSearch
            placeholder={t('pages.clients.selectInbound')}
            filterOption={(input, option) => ((option?.label as string) || '').toLowerCase().includes(input.toLowerCase())}
          />
        </Form.Item>

        <Form.Item label={t('subscription.title')}>
          <Select
            mode="multiple"
            value={form.subscriptionIds}
            onChange={(v) => update('subscriptionIds', v)}
            options={subscriptionOptions}
            showSearch
            placeholder={t('clients.subSelectHint')}
            filterOption={(input, option) => ((option?.label as string) || '').toLowerCase().includes(input.toLowerCase())}
          />
        </Form.Item>

        <Form.Item>
          <Switch checked={form.enable} onChange={(v) => update('enable', v)} />
          <span style={{ marginLeft: 8 }}>{t('enable')}</span>
        </Form.Item>

        {isEdit && ipLimitEnable && (
          <Form.Item label={t('pages.clients.ipLog')}>
            <Space style={{ marginBottom: 8 }}>
              <Button size="small" loading={ipsLoading} onClick={loadIps}>{t('refresh')}</Button>
              <Button size="small" danger loading={ipsClearing} disabled={clientIps.length === 0} onClick={clearIps}>
                {t('pages.clients.clearAll')}
              </Button>
            </Space>
            {clientIps.length > 0 ? (
              <div>
                {clientIps.map((ip, idx) => (
                  <Tag key={idx} color="blue" style={{ marginBottom: 4 }}>{ip}</Tag>
                ))}
              </div>
            ) : (
              <Tag>{t('tgbot.noIpRecord')}</Tag>
            )}
          </Form.Item>
        )}
      </Form>
      </Modal>
    </>
  );
}

// frontend/src/pages/inbounds/ClientFormModal.vue
<script setup>
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import dayjs from 'dayjs';
import { SyncOutlined, RetweetOutlined, DeleteOutlined } from '@ant-design/icons-vue';

import {
  HttpUtil,
  RandomUtil,
  SizeFormatter,
  ColorUtils,
} from '@/utils';
import { Inbound, Protocols, USERS_SECURITY, TLS_FLOW_CONTROL } from '@/models/inbound.js';
import DateTimePicker from '@/components/DateTimePicker.vue';

const { t } = useI18n();

// Add OR edit a single client on a multi-user inbound (VMess / VLess /
// Trojan / Shadowsocks-multi / Hysteria). The legacy panel routes both
// flows through the same modal — same here.
//
// On submit we serialize the client via its toString() (which is just
// JSON.stringify of toJson()) and post it inside a one-element clients
// array so the Go side reuses the same parsing path as the inbound
// settings update.

const props = defineProps({
  open: { type: Boolean, default: false },
  mode: { type: String, default: 'add', validator: (v) => ['add', 'edit'].includes(v) },
  dbInbound: { type: Object, default: null },
  clientIndex: { type: Number, default: null },
  // Sidecar config from the inbounds page — controls visibility of
  // the Subscription, Telegram, and IP-limit fields.
  subEnable: { type: Boolean, default: false },
  tgBotEnable: { type: Boolean, default: false },
  ipLimitEnable: { type: Boolean, default: false },
  trafficDiff: { type: Number, default: 0 },
});

const emit = defineEmits(['update:open', 'saved']);

// === Reactive draft =================================================
const inbound = ref(null);
const client = ref(null);
const oldClientId = ref('');
const clientStats = ref(null);

const saving = ref(false);
const delayedStart = ref(false);

const SECURITY_OPTIONS = Object.values(USERS_SECURITY);
const FLOW_OPTIONS = Object.values(TLS_FLOW_CONTROL);

const protocol = computed(() => inbound.value?.protocol);
const isVmessOrVless = computed(() =>
  protocol.value === Protocols.VMESS || protocol.value === Protocols.VLESS,
);
const isTrojanOrSS = computed(() =>
  protocol.value === Protocols.TROJAN || protocol.value === Protocols.SHADOWSOCKS,
);

const expiryDate = computed({
  get: () => (client.value?.expiryTime > 0 ? dayjs(client.value.expiryTime) : null),
  set: (next) => { if (client.value) client.value.expiryTime = next ? next.valueOf() : 0; },
});

const delayedExpireDays = computed({
  get: () => {
    if (!client.value || client.value.expiryTime >= 0) return 0;
    return client.value.expiryTime / -86400000;
  },
  set: (days) => {
    if (!client.value) return;
    client.value.expiryTime = -86400000 * (days || 0);
  },
});

const totalGB = computed({
  get: () => {
    if (!client.value || !client.value.totalGB) return 0;
    return Math.round((client.value.totalGB / SizeFormatter.ONE_GB) * 100) / 100;
  },
  set: (gb) => {
    if (!client.value) return;
    client.value.totalGB = Math.round((gb || 0) * SizeFormatter.ONE_GB);
  },
});

const isExpired = computed(() => {
  if (props.mode !== 'edit' || !client.value) return false;
  return client.value.expiryTime > 0 && client.value.expiryTime < Date.now();
});
const isTrafficExhausted = computed(() => {
  if (!clientStats.value || clientStats.value.total <= 0) return false;
  return clientStats.value.up + clientStats.value.down >= clientStats.value.total;
});

function getClientId(proto, c) {
  switch (proto) {
    case Protocols.TROJAN: return c.password;
    case Protocols.SHADOWSOCKS: return c.email;
    case Protocols.HYSTERIA: return c.auth;
    default: return c.id;
  }
}

function makeNewClient(proto, parsed) {
  switch (proto) {
    case Protocols.VMESS: return new Inbound.VmessSettings.VMESS();
    case Protocols.VLESS: return new Inbound.VLESSSettings.VLESS();
    case Protocols.TROJAN: return new Inbound.TrojanSettings.Trojan();
    case Protocols.SHADOWSOCKS: {
      const method = parsed.settings.method;
      return new Inbound.ShadowsocksSettings.Shadowsocks(
        method,
        RandomUtil.randomShadowsocksPassword(method),
      );
    }
    case Protocols.HYSTERIA: return new Inbound.HysteriaSettings.Hysteria();
    default: return null;
  }
}

watch(() => props.open, (next) => {
  if (!next) return;
  if (!props.dbInbound) return;
  const parsed = Inbound.fromJson(props.dbInbound.toInbound().toJson());
  inbound.value = parsed;
  delayedStart.value = false;

  if (props.mode === 'edit') {
    const idx = props.clientIndex ?? 0;
    client.value = parsed.clients[idx];
    if (client.value && client.value.expiryTime < 0) delayedStart.value = true;
    oldClientId.value = getClientId(parsed.protocol, client.value);
  } else {
    const c = makeNewClient(parsed.protocol, parsed);
    if (c) parsed.clients.push(c);
    client.value = parsed.clients[parsed.clients.length - 1];
    oldClientId.value = '';
  }

  clientStats.value = (props.dbInbound.clientStats || []).find(
    (s) => s.email === client.value?.email,
  ) || null;
});

function close() {
  emit('update:open', false);
}

function randomEmail() {
  if (client.value) client.value.email = RandomUtil.randomLowerAndNum(9);
}
function randomId() {
  if (client.value) client.value.id = RandomUtil.randomUUID();
}
function randomPassword() {
  if (!client.value || !inbound.value) return;
  if (inbound.value.protocol === Protocols.SHADOWSOCKS) {
    client.value.password = RandomUtil.randomShadowsocksPassword(
      inbound.value.settings.method,
    );
  } else {
    client.value.password = RandomUtil.randomSeq(10);
  }
}
function randomAuth() {
  if (client.value) client.value.auth = RandomUtil.randomSeq(10);
}
function randomSubId() {
  if (client.value) client.value.subId = RandomUtil.randomLowerAndNum(16);
}

const subIdWeak = computed(() => {
  const v = client.value?.subId;
  if (!v) return false;
  return v.length < 8;
});

const clientIpsText = ref('');
async function loadClientIps() {
  if (!client.value?.email) return;
  const msg = await HttpUtil.post(`/panel/api/inbounds/clientIps/${client.value.email}`);
  if (!msg?.success) {
    clientIpsText.value = msg?.obj || '';
    return;
  }
  let ips = msg.obj;
  if (typeof ips === 'string' && ips.startsWith('[') && ips.endsWith(']')) {
    try {
      const parsed = JSON.parse(ips);
      ips = Array.isArray(parsed) ? parsed.join('\n') : ips;
    } catch (_e) {
      // leave as raw
    }
  }
  clientIpsText.value = ips || '';
}
async function clearClientIps() {
  if (!client.value?.email) return;
  const msg = await HttpUtil.post(`/panel/api/inbounds/clearClientIps/${client.value.email}`);
  if (msg?.success) clientIpsText.value = '';
}

async function resetClientTraffic() {
  if (!clientStats.value || !client.value?.email) return;
  const msg = await HttpUtil.post(
    `/panel/api/inbounds/${props.dbInbound.id}/resetClientTraffic/${client.value.email}`,
  );
  if (msg?.success) {
    clientStats.value.up = 0;
    clientStats.value.down = 0;
  }
}

async function submit() {
  if (!client.value || !inbound.value) return;
  saving.value = true;
  try {
    const payload = {
      id: props.dbInbound.id,
      settings: `{"clients": [${client.value.toString(false)}]}`,
    };
    const url = props.mode === 'edit'
      ? `/panel/api/inbounds/updateClient/${oldClientId.value}`
      : '/panel/api/inbounds/addClient';
    const msg = await HttpUtil.post(url, payload);
    if (msg?.success) {
      emit('saved');
      close();
    }
  } finally {
    saving.value = false;
  }
}

const title = computed(() =>
  props.mode === 'edit' ? t('pages.client.edit') : t('pages.client.add'),
);
</script>

<template>
  <a-modal :open="open" :title="title"
    :ok-text="mode === 'edit' ? t('pages.client.submitEdit') : t('pages.client.submitAdd')" :cancel-text="t('close')"
    :confirm-loading="saving" :mask-closable="false" @ok="submit" @cancel="close">
    <a-tag v-if="mode === 'edit' && (isExpired || isTrafficExhausted)" color="red" class="status-banner">
      {{ t('depleted') }}
    </a-tag>

    <a-form v-if="client && inbound" layout="horizontal" :colon="false" :label-col="{ sm: { span: 8 } }"
      :wrapper-col="{ sm: { span: 14 } }">
      <a-form-item :label="t('enable')">
        <a-switch v-model:checked="client.enable" />
      </a-form-item>

      <a-form-item>
        <template #label>
          {{ t('pages.inbounds.email') }}
          <SyncOutlined class="random-icon" @click="randomEmail" />
        </template>
        <a-input v-model:value="client.email" />
      </a-form-item>

      <a-form-item v-if="isTrojanOrSS">
        <template #label>
          {{ t('password') }}
          <SyncOutlined class="random-icon" @click="randomPassword" />
        </template>
        <a-input v-model:value="client.password" />
      </a-form-item>

      <a-form-item v-if="protocol === Protocols.HYSTERIA">
        <template #label>
          {{ t('password') }}
          <SyncOutlined class="random-icon" @click="randomAuth" />
        </template>
        <a-input v-model:value="client.auth" />
      </a-form-item>

      <a-form-item v-if="isVmessOrVless">
        <template #label>
          ID
          <SyncOutlined class="random-icon" @click="randomId" />
        </template>
        <a-input v-model:value="client.id" />
      </a-form-item>

      <a-form-item v-if="protocol === Protocols.VMESS" :label="t('security')">
        <a-select v-model:value="client.security">
          <a-select-option v-for="key in SECURITY_OPTIONS" :key="key" :value="key">
            {{ key }}
          </a-select-option>
        </a-select>
      </a-form-item>

      <a-form-item v-if="client.email && subEnable">
        <template #label>
          {{ t('subscription.title') }}
          <SyncOutlined class="random-icon" @click="randomSubId" />
        </template>
        <a-input v-model:value="client.subId" :status="subIdWeak ? 'warning' : undefined" />
        <div v-if="subIdWeak" style="color:#faad14;font-size:12px;margin-top:4px">
          {{ t('subIdTooShort', 'Subscription ID is too short and may be guessable') }}
        </div>
      </a-form-item>

      <a-form-item v-if="client.email && tgBotEnable" label="Telegram ID">
        <a-input-number v-model:value="client.tgId" :min="0" :style="{ width: '50%' }" />
      </a-form-item>

      <a-form-item v-if="client.email" :label="t('comment')">
        <a-input v-model:value="client.comment" />
      </a-form-item>

      <a-form-item v-if="ipLimitEnable" :label="t('pages.inbounds.IPLimit')">
        <a-input-number v-model:value="client.limitIp" :min="0" />
      </a-form-item>

      <a-form-item v-if="ipLimitEnable && client.limitIp > 0 && client.email && mode === 'edit'"
        :label="t('pages.inbounds.IPLimitlog')">
        <a-textarea v-model:value="clientIpsText" readonly :placeholder="t('pages.inbounds.IPLimitlogDesc')"
          :auto-size="{ minRows: 3, maxRows: 8 }" @click="loadClientIps" />
        <a-button type="link" size="small" danger @click="clearClientIps">
          <template #icon>
            <DeleteOutlined />
          </template>
          {{ t('pages.inbounds.IPLimitlogclear') }}
        </a-button>
      </a-form-item>

      <a-form-item v-if="inbound.canEnableTlsFlow()" label="Flow">
        <a-select v-model:value="client.flow">
          <a-select-option value="">{{ t('none') }}</a-select-option>
          <a-select-option v-for="key in FLOW_OPTIONS" :key="key" :value="key">
            {{ key }}
          </a-select-option>
        </a-select>
      </a-form-item>

      <a-form-item v-if="protocol === Protocols.VLESS" label="Reverse tag">
        <a-input v-model:value="client.reverseTag" placeholder="Optional reverse tag" />
      </a-form-item>

      <a-form-item>
        <template #label>
          <a-tooltip :title="t('pages.inbounds.meansNoLimit')">{{ t('pages.inbounds.totalFlow') }}</a-tooltip>
        </template>
        <a-input-number v-model:value="totalGB" :min="0" :step="0.1" />
      </a-form-item>

      <a-form-item v-if="mode === 'edit' && clientStats" :label="t('usage')">
        <a-tag :color="ColorUtils.clientUsageColor(clientStats, trafficDiff)">
          {{ SizeFormatter.sizeFormat(clientStats.up) }} /
          {{ SizeFormatter.sizeFormat(clientStats.down) }}
          ({{ SizeFormatter.sizeFormat(clientStats.up + clientStats.down) }})
        </a-tag>
        <a-tooltip v-if="client.email" :title="t('pages.inbounds.resetTraffic')">
          <RetweetOutlined class="action-icon" @click="resetClientTraffic" />
        </a-tooltip>
      </a-form-item>

      <a-form-item :label="t('pages.client.delayedStart')">
        <a-switch v-model:checked="delayedStart" @click="client.expiryTime = 0" />
      </a-form-item>

      <a-form-item v-if="delayedStart" :label="t('pages.client.expireDays')">
        <a-input-number v-model:value="delayedExpireDays" :min="0" />
      </a-form-item>

      <a-form-item v-else>
        <template #label>
          <a-tooltip :title="t('pages.inbounds.leaveBlankToNeverExpire')">{{ t('pages.inbounds.expireDate')
          }}</a-tooltip>
        </template>
        <DateTimePicker v-model:value="expiryDate" />
        <a-tag v-if="mode === 'edit' && isExpired" color="red">{{ t('depleted') }}</a-tag>
      </a-form-item>

      <a-form-item v-if="client.expiryTime !== 0">
        <template #label>
          <a-tooltip :title="t('pages.client.renewDesc')">{{ t('pages.client.renew') }}</a-tooltip>
        </template>
        <a-input-number v-model:value="client.reset" :min="0" />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<style scoped>
.status-banner {
  display: block;
  margin-bottom: 10px;
  text-align: center;
}

.random-icon,
.action-icon {
  margin-left: 4px;
  cursor: pointer;
  color: var(--ant-primary-color, #1890ff);
}
</style>
