// frontend/src/pages/inbounds/QrPanel.vue
<script setup>
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { CopyOutlined, DownloadOutlined, PictureOutlined } from '@ant-design/icons-vue';
import { message } from 'ant-design-vue';

import { ClipboardManager, FileManager } from '@/utils';
import { theme as themeState } from '@/composables/useTheme.js';

const { t } = useI18n();

const props = defineProps({
  value: { type: String, required: true },
  remark: { type: String, default: '' },
  downloadName: { type: String, default: '' },
  size: { type: Number, default: 360 },
  showQr: { type: Boolean, default: true },
});

const qrRef = ref(null);

// QR colours adapt to theme
const qrColor = computed(() => (themeState.isDark || themeState.isUltra) ? '#fff' : '#000');
const qrBg = computed(() => {
  if (themeState.isUltra) return '#0c0e12';
  if (themeState.isDark) return '#252526';
  return '#ffffff';
});

async function copy() {
  const ok = await ClipboardManager.copyText(props.value);
  if (ok) message.success(t('copied'));
}

function download() {
  if (!props.downloadName) return;
  FileManager.downloadTextFile(props.value, props.downloadName);
}

function svgToPngBlob(size = 360) {
  const svgEl = qrRef.value?.querySelector('svg');
  if (!svgEl) return Promise.resolve(null);
  const svgData = new XMLSerializer().serializeToString(svgEl);
  const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = size;
      canvas.height = size;
      const ctx = canvas.getContext('2d');
      ctx.fillStyle = qrBg.value;
      ctx.fillRect(0, 0, size, size);
      ctx.drawImage(img, 0, 0, size, size);
      URL.revokeObjectURL(url);
      canvas.toBlob(resolve, 'image/png');
    };
    img.onerror = () => { URL.revokeObjectURL(url); resolve(null); };
    img.src = url;
  });
}

async function copyImage() {
  const blob = await svgToPngBlob(props.size);
  if (!blob) return;
  try {
    await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]);
    message.success(t('copied'));
  } catch {
    downloadImageBlob(blob);
  }
}

function downloadImageBlob(blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${props.remark || 'qrcode'}.png`;
  link.click();
  URL.revokeObjectURL(url);
}

async function downloadImage() {
  const blob = await svgToPngBlob(props.size);
  if (blob) downloadImageBlob(blob);
}
</script>

<template>
  <div class="qr-panel">
    <div class="qr-panel-header">
      <a-tag color="green" class="qr-remark">{{ remark }}</a-tag>
      <a-tooltip :title="t('copy')">
        <a-button size="small" @click="copy">
          <template #icon>
            <CopyOutlined />
          </template>
        </a-button>
      </a-tooltip>
      <a-tooltip v-if="showQr" :title="t('downloadImage', 'Download Image')">
        <a-button size="small" @click="downloadImage">
          <template #icon>
            <PictureOutlined />
          </template>
        </a-button>
      </a-tooltip>
      <a-tooltip v-if="downloadName" :title="t('download')">
        <a-button size="small" @click="download">
          <template #icon>
            <DownloadOutlined />
          </template>
        </a-button>
      </a-tooltip>
    </div>
    <div v-if="showQr" ref="qrRef" class="qr-panel-canvas">
      <a-tooltip :title="t('copy')">
        <a-qrcode class="qr-code" :value="value" :size="size" type="svg" :bordered="false"
          :color="qrColor" :bg-color="qrBg" @click="copyImage" />
      </a-tooltip>
    </div>
  </div>
</template>

<style scoped>
.qr-panel {
  color-scheme: only light;
  border: 1px solid rgba(128, 128, 128, 0.2);
  border-radius: 8px;
  padding: 10px;
  margin-bottom: 10px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.qr-panel-header {
  display: flex;
  align-items: center;
  gap: 6px;
  flex-wrap: wrap;
}

.qr-remark {
  margin: 0;
}

.qr-panel-canvas {
  display: flex;
  justify-content: center;
  padding: 6px 0;
}

.qr-panel-canvas .qr-code {
  cursor: pointer;
  background: transparent;
  border-radius: 4px;
  line-height: 0;
}

.qr-panel-canvas .qr-code :deep(svg) {
  display: block;
  width: 100%;
  height: auto;
  max-width: 360px;
}
</style>

// frontend/src/pages/inbounds/QrPanel.tsx
import { useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, QRCode, Tag, Tooltip, message } from 'antd';
import { CopyOutlined, DownloadOutlined, PictureOutlined } from '@ant-design/icons';

import { ClipboardManager, FileManager } from '@/utils';
import './QrPanel.css';

interface QrPanelProps {
  value: string;
  remark?: string;
  downloadName?: string;
  size?: number;
  showQr?: boolean;
}

async function svgToPngBlob(svgEl: SVGSVGElement | null, size: number): Promise<Blob | null> {
  if (!svgEl) return null;
  const svgData = new XMLSerializer().serializeToString(svgEl);
  const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);
  return new Promise<Blob | null>((resolve) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = size;
      canvas.height = size;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        URL.revokeObjectURL(url);
        resolve(null);
        return;
      }
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, size, size);
      ctx.drawImage(img, 0, 0, size, size);
      URL.revokeObjectURL(url);
      canvas.toBlob((blob) => resolve(blob), 'image/png');
    };
    img.onerror = () => { URL.revokeObjectURL(url); resolve(null); };
    img.src = url;
  });
}

function downloadImageBlob(blob: Blob, remark: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${remark || 'qrcode'}.png`;
  link.click();
  URL.revokeObjectURL(url);
}

export default function QrPanel({
  value,
  remark = '',
  downloadName = '',
  size = 360,
  showQr = true,
}: QrPanelProps) {
  const { t } = useTranslation();
  const [messageApi, messageContextHolder] = message.useMessage();
  const qrRef = useRef<HTMLDivElement | null>(null);

  async function copy() {
    const ok = await ClipboardManager.copyText(value);
    if (ok) messageApi.success(t('copied'));
  }

  function download() {
    if (!downloadName) return;
    FileManager.downloadTextFile(value, downloadName);
  }

  async function copyImage() {
    const blob = await getQrBlob();
    if (!blob) return;
    try {
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]);
      messageApi.success(t('copiedQrImage'));
    } catch {
      downloadImageBlob(blob, remark);
    }
  }

  async function downloadImage() {
    const blob = await getQrBlob();
    if (blob) downloadImageBlob(blob, remark);
  }

  async function getQrBlob(): Promise<Blob | null> {
    const canvas = qrRef.current?.querySelector('canvas') as HTMLCanvasElement | null;
    if (canvas) return new Promise((resolve) => canvas.toBlob(resolve, 'image/png'));
    const svgEl = qrRef.current?.querySelector('svg') as SVGSVGElement | null;
    if (svgEl) return svgToPngBlob(svgEl, size);
    return null;
  }

  return (
    <div className="qr-panel">
      {messageContextHolder}
      <div className="qr-panel-header">
        <Tag color="green" className="qr-remark">{remark}</Tag>
        <Tooltip title={t('copy')}>
          <Button size="small" icon={<CopyOutlined />} onClick={copy} />
        </Tooltip>
        {showQr && (
          <Tooltip title={t('downloadImage') !== 'downloadImage' ? t('downloadImage') : 'Download Image'}>
            <Button size="small" icon={<PictureOutlined />} onClick={downloadImage} />
          </Tooltip>
        )}
        {downloadName && (
          <Tooltip title={t('download')}>
            <Button size="small" icon={<DownloadOutlined />} onClick={download} />
          </Tooltip>
        )}
      </div>
      {showQr && (
        <div ref={qrRef} className="qr-panel-canvas">
          <Tooltip title={t('clickToCopyImage')}>
            <QRCode
              className="qr-code"
              value={value}
              size={size}
              type="canvas"
              bordered={false}
              color="#000000"
              bgColor="#ffffff"
              onClick={copyImage}
            />
          </Tooltip>
        </div>
      )}
    </div>
  );
}
