// frontend/src/pages/xray/XrayPage.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Alert,
  Button,
  Card,
  Col,
  ConfigProvider,
  FloatButton,
  Layout,
  message,
  Modal,
  Popover,
  Radio,
  Result,
  Row,
  Space,
  Spin,
  Tabs,
  Tooltip,
} from 'antd';
import {
  SettingOutlined,
  SwapOutlined,
  UploadOutlined,
  ClusterOutlined,
  DatabaseOutlined,
  CodeOutlined,
  QuestionCircleOutlined,
} from '@ant-design/icons';

import { useTheme } from '@/hooks/useTheme';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import { useWebSocket } from '@/hooks/useWebSocket';
import { useXraySetting } from '@/hooks/useXraySetting';
import { useAllSetting } from '@/hooks/useAllSetting';
import type { XraySettingsValue } from '@/hooks/useXraySetting';
import AppSidebar from '@/components/AppSidebar';
import JsonEditor from '@/components/JsonEditor';
import { setMessageInstance } from '@/utils/messageBus';
import { HttpUtil } from '@/utils';

import BasicsTab from './BasicsTab';
import RoutingTab from './RoutingTab';
import OutboundsTab from './OutboundsTab';
import BalancersTab from './BalancersTab';
import DnsTab from './DnsTab';
import WarpModal from './WarpModal';
import NordModal from './NordModal';
import '@/styles/page-cards.css';
import './XrayPage.css';

const TAB_KEYS = ['tpl-basic', 'tpl-routing', 'tpl-outbound', 'tpl-balancer', 'tpl-dns', 'tpl-advanced'];
const SLUG_BY_KEY: Record<string, string> = {
  'tpl-basic': 'basic',
  'tpl-routing': 'routing',
  'tpl-outbound': 'outbound',
  'tpl-balancer': 'balancer',
  'tpl-dns': 'dns',
  'tpl-advanced': 'advanced',
};
const KEY_BY_SLUG: Record<string, string> = Object.fromEntries(
  Object.entries(SLUG_BY_KEY).map(([k, v]) => [v, k]),
);

type AdvKey = 'xraySetting' | 'inboundSettings' | 'outboundSettings' | 'routingRuleSettings';

export default function XrayPage() {
  const { t } = useTranslation();
  const { isDark, isUltra, antdThemeConfig } = useTheme();
  const { isMobile } = useMediaQuery();
  const [messageApi, messageContextHolder] = message.useMessage();
  useEffect(() => { setMessageInstance(messageApi); }, [messageApi]);
  const xs = useXraySetting();
  const {
    fetched,
    spinning,
    saveDisabled,
    fetchError,
    xraySetting,
    setXraySetting,
    templateSettings,
    setTemplateSettings,
    outboundTestUrl,
    setOutboundTestUrl,
    inboundTags,
    clientReverseTags,
    restartResult,
    outboundsTraffic,
    outboundTestStates,
    testingAll,
    fetchAll,
    resetOutboundsTraffic,
    applyOutboundsEvent,
    testOutbound,
    testAllOutbounds,
    saveAll,
    resetToDefault,
    restartXray,
  } = xs;

  const { allSetting, updateSetting } = useAllSetting();

  const onChangeXrayAutoUpdate = useCallback(async (value: boolean) => {
    updateSetting({ xrayAutoUpdate: value } as Partial<typeof allSetting>);
    allSetting.xrayAutoUpdate = value;
    await HttpUtil.post('/panel/setting/update', allSetting);
  }, [allSetting, updateSetting]);

  const onChangeXrayUpdateCron = useCallback(async (value: string) => {
    updateSetting({ xrayUpdateCron: value } as Partial<typeof allSetting>);
    allSetting.xrayUpdateCron = value;
    await HttpUtil.post('/panel/setting/update', allSetting);
  }, [allSetting, updateSetting]);

  useWebSocket({ outbounds: applyOutboundsEvent as never });

  const [modal, modalContextHolder] = Modal.useModal();
  const [warpOpen, setWarpOpen] = useState(false);
  const [nordOpen, setNordOpen] = useState(false);
  const [advSettings, setAdvSettings] = useState<AdvKey>('xraySetting');
  const [activeTabKey, setActiveTabKey] = useState(() => {
    const slug = window.location.hash.slice(1);
    return KEY_BY_SLUG[slug] || TAB_KEYS[0];
  });

  useEffect(() => {
    function syncTabFromHash() {
      const key = KEY_BY_SLUG[window.location.hash.slice(1)];
      if (key) setActiveTabKey(key);
    }
    window.addEventListener('hashchange', syncTabFromHash);
    return () => window.removeEventListener('hashchange', syncTabFromHash);
  }, []);

  function onTabChange(key: string) {
    setActiveTabKey(key);
    const slug = SLUG_BY_KEY[key];
    if (slug && window.location.hash !== `#${slug}`) {
      history.replaceState(null, '', `#${slug}`);
    }
  }

  const mutate = useCallback(
    (mutator: (next: XraySettingsValue) => void) => {
      setTemplateSettings((prev) => {
        if (!prev) return prev;
        const clone = JSON.parse(JSON.stringify(prev)) as XraySettingsValue;
        mutator(clone);
        return clone;
      });
    },
    [setTemplateSettings],
  );

  const warpExist = !!templateSettings?.outbounds?.find((o) => o?.tag === 'warp');
  const nordExist = !!templateSettings?.outbounds?.find((o) => o?.tag?.startsWith?.('nord-'));

  const basePath = window.X_UI_BASE_PATH || '';
  const requestUri = window.location.pathname;

  async function onTestOutbound(idx: number, mode: string) {
    const outbound = templateSettings?.outbounds?.[idx];
    if (outbound) await testOutbound(idx, outbound, mode);
  }

  function onAddOutbound(outbound: Record<string, unknown>) {
    mutate((tt) => {
      if (!Array.isArray(tt.outbounds)) tt.outbounds = [];
      tt.outbounds.push(outbound as never);
    });
  }
  function onResetOutbound(payload: { index: number; outbound: Record<string, unknown>; oldTag?: string; newTag?: string }) {
    mutate((tt) => {
      if (!tt.outbounds || payload.index < 0) return;
      tt.outbounds[payload.index] = payload.outbound as never;
      if (payload.oldTag && payload.newTag && payload.oldTag !== payload.newTag) {
        const rules = tt.routing?.rules || [];
        for (const r of rules) {
          if (r?.outboundTag === payload.oldTag) r.outboundTag = payload.newTag;
        }
      }
    });
  }
  function onRemoveOutboundByTag(tag: string) {
    mutate((tt) => {
      if (!tt.outbounds) return;
      const idx = tt.outbounds.findIndex((o) => o?.tag === tag);
      if (idx >= 0) tt.outbounds.splice(idx, 1);
    });
  }
  function onRemoveOutboundByIndex(index: number) {
    mutate((tt) => {
      if (tt.outbounds && index >= 0) tt.outbounds.splice(index, 1);
    });
  }
  function onRemoveRoutingRules(payload: { prefix: string }) {
    mutate((tt) => {
      const rules = tt.routing?.rules;
      if (!Array.isArray(rules)) return;
      tt.routing!.rules = rules.filter((r) => !r?.outboundTag?.startsWith?.(payload.prefix));
    });
  }

  const advancedText = useMemo(() => {
    if (advSettings === 'xraySetting') return xraySetting;
    const tpl = templateSettings;
    if (!tpl) return '';
    try {
      switch (advSettings) {
        case 'inboundSettings': return JSON.stringify(tpl.inbounds || [], null, 2);
        case 'outboundSettings': return JSON.stringify(tpl.outbounds || [], null, 2);
        case 'routingRuleSettings': return JSON.stringify(tpl.routing?.rules || [], null, 2);
        default: return '';
      }
    } catch {
      return '';
    }
  }, [advSettings, xraySetting, templateSettings]);

  function onAdvancedTextChange(next: string) {
    if (advSettings === 'xraySetting') {
      setXraySetting(next);
      return;
    }
    let parsed;
    try {
      parsed = JSON.parse(next);
    } catch {
      return;
    }
    mutate((tt) => {
      switch (advSettings) {
        case 'inboundSettings':
          tt.inbounds = parsed;
          break;
        case 'outboundSettings':
          tt.outbounds = parsed;
          break;
        case 'routingRuleSettings':
          if (!tt.routing) tt.routing = {};
          tt.routing.rules = parsed;
          break;
      }
    });
  }

  function confirmRestart() {
    modal.confirm({
      title: t('pages.xray.restartConfirmTitle'),
      content: t('pages.xray.restartConfirmContent'),
      okText: t('pages.inbounds.restartXray'),
      cancelText: t('cancel'),
      onOk: () => restartXray(),
    });
  }

  function onSaveAll() {
    try {
      JSON.parse(xraySetting);
    } catch (e) {
      messageApi.error(`Advanced JSON: ${(e as Error).message}`);
      setActiveTabKey('tpl-advanced');
      return;
    }
    saveAll();
  }

  const scrollTarget = () => document.getElementById('content-layout') || window;

  const pageClass = `xray-page ${isDark ? 'is-dark' : ''} ${isUltra ? 'is-ultra' : ''}`.trim();

  return (
    <ConfigProvider theme={antdThemeConfig}>
      {messageContextHolder}
      {modalContextHolder}
      <Layout className={pageClass}>
        <AppSidebar basePath={basePath} requestUri={requestUri} />

        <Layout className="content-shell">
          <Layout.Content id="content-layout" className="content-area">
            <Spin spinning={spinning || !fetched} delay={200} description={t('loading')} size="large">
              {!fetched ? (
                <div className="loading-spacer" />
              ) : fetchError ? (
                <Result
                  status="error"
                  title={t('somethingWentWrong')}
                  subTitle={fetchError}
                  extra={<Button type="primary" onClick={fetchAll}>{t('check')}</Button>}
                />
              ) : (
                <Row gutter={[isMobile ? 8 : 16, isMobile ? 0 : 12]}>
                  <Col span={24}>
                    <Card hoverable>
                      <Row className="header-row">
                        <Col xs={24} sm={14} className="header-actions">
                          <Space>
                            <Button type="primary" disabled={saveDisabled} onClick={onSaveAll}>
                              {t('pages.xray.save')}
                            </Button>
                            <Button type="primary" danger disabled={!saveDisabled} onClick={confirmRestart}>
                              {t('pages.xray.restart')}
                            </Button>
                            {restartResult && (
                              <Popover
                                placement="rightTop"
                                title={t('pages.xray.restartOutput')}
                                content={<pre className="restart-result">{restartResult}</pre>}
                              >
                                <QuestionCircleOutlined className="restart-icon" />
                              </Popover>
                            )}
                          </Space>
                        </Col>
                        <Col xs={24} sm={10} className="header-info">
                          <FloatButton.BackTop target={scrollTarget} visibilityHeight={200} />
                          <Alert type="warning" showIcon title={t('pages.settings.infoDesc')} />
                        </Col>
                      </Row>
                    </Card>
                  </Col>

                  <Col span={24}>
                    <Card hoverable>
                    <Tabs
                      activeKey={activeTabKey}
                      onChange={onTabChange}
                      className={isMobile ? 'icons-only' : ''}
                      items={[
                        {
                          key: 'tpl-basic',
                          label: (
                            <Tooltip title={isMobile ? t('pages.xray.basicTemplate') : ''}>
                              <SettingOutlined />
                              {!isMobile && <span>{` ${t('pages.xray.basicTemplate')}`}</span>}
                            </Tooltip>
                          ),
                          children: (
                            <BasicsTab
                              templateSettings={templateSettings}
                              setTemplateSettings={setTemplateSettings}
                              outboundTestUrl={outboundTestUrl}
                              onChangeOutboundTestUrl={setOutboundTestUrl}
                              warpExist={warpExist}
                              nordExist={nordExist}
                              onShowWarp={() => setWarpOpen(true)}
                              onShowNord={() => setNordOpen(true)}
                              onResetDefault={resetToDefault}
                              xrayAutoUpdate={allSetting.xrayAutoUpdate}
                              xrayUpdateCron={allSetting.xrayUpdateCron}
                              timeLocation={allSetting.timeLocation}
                              onChangeXrayAutoUpdate={onChangeXrayAutoUpdate}
                              onChangeXrayUpdateCron={onChangeXrayUpdateCron}
                            />
                          ),
                        },
                        {
                          key: 'tpl-routing',
                          label: (
                            <Tooltip title={isMobile ? t('pages.xray.Routings') : ''}>
                              <SwapOutlined />
                              {!isMobile && <span>{` ${t('pages.xray.Routings')}`}</span>}
                            </Tooltip>
                          ),
                          children: (
                            <RoutingTab
                              templateSettings={templateSettings}
                              setTemplateSettings={setTemplateSettings}
                              inboundTags={inboundTags}
                              clientReverseTags={clientReverseTags}
                              isMobile={isMobile}
                            />
                          ),
                        },
                        {
                          key: 'tpl-outbound',
                          label: (
                            <Tooltip title={isMobile ? t('pages.xray.Outbounds') : ''}>
                              <UploadOutlined />
                              {!isMobile && <span>{` ${t('pages.xray.Outbounds')}`}</span>}
                            </Tooltip>
                          ),
                          children: (
                            <OutboundsTab
                              templateSettings={templateSettings}
                              setTemplateSettings={setTemplateSettings}
                              outboundsTraffic={outboundsTraffic}
                              outboundTestStates={outboundTestStates}
                              testingAll={testingAll}
                              inboundTags={inboundTags}
                              isMobile={isMobile}
                              onResetTraffic={resetOutboundsTraffic}
                              onTest={onTestOutbound}
                              onTestAll={testAllOutbounds}
                              onShowWarp={() => setWarpOpen(true)}
                              onShowNord={() => setNordOpen(true)}
                            />
                          ),
                        },
                        {
                          key: 'tpl-balancer',
                          label: (
                            <Tooltip title={isMobile ? t('pages.xray.Balancers') : ''}>
                              <ClusterOutlined />
                              {!isMobile && <span>{` ${t('pages.xray.Balancers')}`}</span>}
                            </Tooltip>
                          ),
                          children: (
                            <BalancersTab
                              templateSettings={templateSettings}
                              setTemplateSettings={setTemplateSettings}
                              clientReverseTags={clientReverseTags}
                              isMobile={isMobile}
                            />
                          ),
                        },
                        {
                          key: 'tpl-dns',
                          label: (
                            <Tooltip title={isMobile ? t('pages.xray.dnsTab') : ''}>
                              <DatabaseOutlined />
                              {!isMobile && <span> {t('pages.xray.dnsTab')}</span>}
                            </Tooltip>
                          ),
                          children: (
                            <DnsTab
                              templateSettings={templateSettings}
                              setTemplateSettings={setTemplateSettings}
                            />
                          ),
                        },
                        {
                          key: 'tpl-advanced',
                          label: (
                            <Tooltip title={isMobile ? t('pages.xray.advancedTemplate') : ''}>
                              <CodeOutlined />
                              {!isMobile && <span>{` ${t('pages.xray.advancedTemplate')}`}</span>}
                            </Tooltip>
                          ),
                          children: (
                            <>
                              <div className="advanced-meta">
                                <h4>{t('pages.xray.Template')}</h4>
                                <p>{t('pages.xray.TemplateDesc')}</p>
                              </div>
                              <Radio.Group
                                value={advSettings}
                                buttonStyle="solid"
                                size={isMobile ? 'small' : 'middle'}
                                style={{ margin: '12px 0' }}
                                onChange={(e) => setAdvSettings(e.target.value)}
                              >
                                <Radio.Button value="xraySetting">{t('pages.xray.completeTemplate')}</Radio.Button>
                                <Radio.Button value="inboundSettings">{t('pages.xray.Inbounds')}</Radio.Button>
                                <Radio.Button value="outboundSettings">{t('pages.xray.Outbounds')}</Radio.Button>
                                <Radio.Button value="routingRuleSettings">{t('pages.xray.Routings')}</Radio.Button>
                              </Radio.Group>
                              <JsonEditor
                                value={advancedText}
                                onChange={onAdvancedTextChange}
                                minHeight="420px"
                                maxHeight="720px"
                              />
                            </>
                          ),
                        },
                      ]}
                    />
                    </Card>
                  </Col>
                </Row>
              )}
            </Spin>
          </Layout.Content>
        </Layout>

        <WarpModal
          open={warpOpen}
          templateSettings={templateSettings}
          onClose={() => setWarpOpen(false)}
          onAddOutbound={onAddOutbound}
          onResetOutbound={onResetOutbound}
          onRemoveOutbound={onRemoveOutboundByTag}
        />
        <NordModal
          open={nordOpen}
          templateSettings={templateSettings}
          onClose={() => setNordOpen(false)}
          onAddOutbound={onAddOutbound}
          onResetOutbound={onResetOutbound}
          onRemoveOutbound={onRemoveOutboundByIndex}
          onRemoveRoutingRules={onRemoveRoutingRules}
        />
      </Layout>
    </ConfigProvider>
  );
}

// frontend/src/pages/xray/XrayPage.vue
<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { Modal, message } from 'ant-design-vue';
import {
  SettingOutlined,
  SwapOutlined,
  UploadOutlined,
  ClusterOutlined,
  DatabaseOutlined,
  CodeOutlined,
  QuestionCircleOutlined,
} from '@ant-design/icons-vue';

import { theme as themeState, antdThemeConfig } from '@/composables/useTheme.js';
import { useMediaQuery } from '@/composables/useMediaQuery.js';
import AppSidebar from '@/components/AppSidebar.vue';
import BasicsTab from './BasicsTab.vue';
import RoutingTab from './RoutingTab.vue';
import OutboundsTab from './OutboundsTab.vue';
import BalancersTab from './BalancersTab.vue';
import DnsTab from './DnsTab.vue';
import WarpModal from './WarpModal.vue';
import NordModal from './NordModal.vue';
import JsonEditor from '@/components/JsonEditor.vue';
import { useXraySetting } from './useXraySetting.js';
import { useWebSocket } from '@/composables/useWebSocket.js';
import { useAllSetting } from '@/pages/settings/useAllSetting.js';

const { t } = useI18n();

const {
  fetched,
  spinning,
  saveDisabled,
  fetchError,
  xraySetting,
  templateSettings,
  outboundTestUrl,
  inboundTags,
  clientReverseTags,
  restartResult,
  outboundsTraffic,
  outboundTestStates,
  testingAll,
  fetchAll,
  resetOutboundsTraffic,
  testOutbound,
  testAllOutbounds,
  saveAll,
  resetToDefault,
  restartXray,
  applyOutboundsEvent,
} = useXraySetting();

const {
  allSetting,
} = useAllSetting();

useWebSocket({ outbounds: applyOutboundsEvent });

async function onTestOutbound(idx, mode = 'tcp') {
  const outbound = templateSettings.value?.outbounds?.[idx];
  if (outbound) await testOutbound(idx, outbound, mode);
}

async function onTestAllOutbounds(mode = 'tcp') {
  await testAllOutbounds(mode);
}

function onDeleteOutbound(idx) {
  templateSettings.value.outbounds.splice(idx, 1);
  outboundTestStates.value = Object.fromEntries(
    Object.entries(outboundTestStates.value)
      .filter(([k]) => Number(k) !== idx)
      .map(([k, v]) => [Number(k) > idx ? Number(k) - 1 : Number(k), v]),
  );
}

// === Advanced tab — radio-driven view ==============================
// Mirrors the legacy advanced page: a 4-way radio toggles which slice
// of the xray config the textarea edits — the full config, just the
// inbounds, just the outbounds, or just the routing rules. Each slice
// reads/writes through templateSettings so edits propagate to the
// dirty-poll and structured tabs.
const advSettings = ref('xraySetting');

const advancedText = computed({
  get: () => {
    if (advSettings.value === 'xraySetting') return xraySetting.value;
    const t = templateSettings.value;
    if (!t) return '';
    try {
      switch (advSettings.value) {
        case 'inboundSettings':
          return JSON.stringify(t.inbounds || [], null, 2);
        case 'outboundSettings':
          return JSON.stringify(t.outbounds || [], null, 2);
        case 'routingRuleSettings':
          return JSON.stringify(t.routing?.rules || [], null, 2);
        default:
          return '';
      }
    } catch (_e) {
      return '';
    }
  },
  set: (next) => {
    if (advSettings.value === 'xraySetting') {
      xraySetting.value = next;
      return;
    }
    // Slice edits: parse-then-merge into templateSettings so the
    // structured tabs and the dirty-poll re-stringify it cleanly.
    let parsed;
    try { parsed = JSON.parse(next); } catch (_e) { return; }
    const t = templateSettings.value;
    if (!t) return;
    switch (advSettings.value) {
      case 'inboundSettings':
        t.inbounds = parsed;
        break;
      case 'outboundSettings':
        t.outbounds = parsed;
        break;
      case 'routingRuleSettings':
        if (!t.routing) t.routing = {};
        t.routing.rules = parsed;
        break;
    }
  },
});

// `WarpExist` / `NordExist` derive from the parsed templateSettings —
// the Basics tab gates its WARP / NordVPN domain selectors on whether
// the matching outbound is provisioned, falling back to a "configure"
// button that today just toasts (the modals land in 6-v).
const warpExist = computed(
  () => !!templateSettings.value?.outbounds?.find((o) => o?.tag === 'warp'),
);
const nordExist = computed(
  () => !!templateSettings.value?.outbounds?.find((o) => o?.tag?.startsWith?.('nord-')),
);

// === WARP / NordVPN provisioning modals ============================
const warpOpen = ref(false);
const nordOpen = ref(false);

function showWarp() { warpOpen.value = true; }
function showNord() { nordOpen.value = true; }

function ensureOutbounds() {
  if (!templateSettings.value) return null;
  if (!Array.isArray(templateSettings.value.outbounds)) {
    templateSettings.value.outbounds = [];
  }
  return templateSettings.value.outbounds;
}

function onAddOutbound(outbound) {
  const list = ensureOutbounds();
  if (list) list.push(outbound);
}
function onResetOutbound({ index, outbound, oldTag, newTag }) {
  const list = ensureOutbounds();
  if (!list || index < 0) return;
  list[index] = outbound;
  // Tag rename across routing rules — preserves Nord's
  // server-switch flow without dangling references.
  if (oldTag && newTag && oldTag !== newTag) {
    const rules = templateSettings.value?.routing?.rules || [];
    for (const r of rules) {
      if (r?.outboundTag === oldTag) r.outboundTag = newTag;
    }
  }
}
function onRemoveOutboundByTag(tag) {
  const list = ensureOutbounds();
  if (!list) return;
  const idx = list.findIndex((o) => o?.tag === tag);
  if (idx >= 0) list.splice(idx, 1);
}
function onRemoveOutboundByIndex(index) {
  const list = ensureOutbounds();
  if (list && index >= 0) list.splice(index, 1);
}
function onRemoveRoutingRules({ prefix }) {
  const rules = templateSettings.value?.routing?.rules;
  if (!Array.isArray(rules)) return;
  templateSettings.value.routing.rules = rules.filter(
    (r) => !r?.outboundTag?.startsWith?.(prefix),
  );
}

const { isMobile } = useMediaQuery();

const basePath = window.X_UI_BASE_PATH || '';
const requestUri = window.location.pathname;

// See SettingsPage scrollTarget — wrap so `document` is in scope.
function scrollTarget() {
  return document.getElementById('content-layout');
}

function confirmRestart() {
  Modal.confirm({
    title: t('pages.xray.restartConfirmTitle'),
    content: t('pages.xray.restartConfirmDesc'),
    okText: t('pages.xray.restart'),
    cancelText: t('cancel'),
    onOk: () => restartXray(),
  });
}

const tabKeys = ['tpl-basic', 'tpl-routing', 'tpl-outbound', 'tpl-balancer', 'tpl-dns', 'tpl-advanced'];
const slugByKey = {
  'tpl-basic': 'basic',
  'tpl-routing': 'routing',
  'tpl-outbound': 'outbound',
  'tpl-balancer': 'balancer',
  'tpl-dns': 'dns',
  'tpl-advanced': 'advanced',
};
const keyBySlug = Object.fromEntries(Object.entries(slugByKey).map(([k, v]) => [v, k]));

const activeTabKey = ref(keyBySlug[window.location.hash.slice(1)] || tabKeys[0]);

function onTabChange(key) {
  activeTabKey.value = key;
  const slug = slugByKey[key];
  if (slug && window.location.hash !== `#${slug}`) {
    history.replaceState(null, '', `#${slug}`);
  }
}

function onSaveAll() {
  try {
    JSON.parse(xraySetting.value);
  } catch (e) {
    message.error(`Advanced JSON: ${e.message}`);
    activeTabKey.value = 'tpl-advanced';
    return;
  }
  saveAll();
}

function syncTabFromHash() {
  const key = keyBySlug[window.location.hash.slice(1)];
  if (key) activeTabKey.value = key;
}

onMounted(() => {
  window.addEventListener('hashchange', syncTabFromHash);
});

onBeforeUnmount(() => {
  window.removeEventListener('hashchange', syncTabFromHash);
});
</script>

<template>
  <a-config-provider :theme="antdThemeConfig">
    <a-layout class="xray-page" :class="{ 'is-dark': themeState.isDark, 'is-ultra': themeState.isUltra }">
      <AppSidebar :base-path="basePath" :request-uri="requestUri" />

      <a-layout class="content-shell">
        <a-layout-content id="content-layout" class="content-area">
          <a-spin :spinning="spinning || !fetched" :delay="200" tip="Loading…" size="large">
            <div v-if="!fetched" class="loading-spacer" />

            <a-result v-else-if="fetchError" status="error" :title="t('somethingWentWrong')" :sub-title="fetchError">
              <template #extra>
                <a-button type="primary" @click="fetchAll">{{ t('check') }}</a-button>
              </template>
            </a-result>

            <template v-else>
              <a-row :gutter="[isMobile ? 8 : 16, isMobile ? 0 : 12]">
                <!-- Save / Restart bar -->
                <a-col :span="24">
                  <a-card hoverable>
                    <a-row class="header-row">
                      <a-col :xs="24" :sm="14" class="header-actions">
                        <a-space direction="horizontal">
                          <a-button type="primary" :disabled="saveDisabled" @click="onSaveAll">
                            {{ t('pages.xray.save') }}
                          </a-button>
                          <a-button type="primary" danger :disabled="!saveDisabled" @click="confirmRestart">
                            {{ t('pages.xray.restart') }}
                          </a-button>
                          <a-popover v-if="restartResult" placement="rightTop">
                            <template #title>{{ t('pages.xray.restartOutput') }}</template>
                            <template #content>
                              <pre class="restart-result">{{ restartResult }}</pre>
                            </template>
                            <QuestionCircleOutlined class="restart-icon" />
                          </a-popover>
                        </a-space>
                      </a-col>
                      <a-col :xs="24" :sm="10" class="header-info">
                        <a-back-top :target="scrollTarget" :visibility-height="200" />
                        <a-alert type="warning" show-icon :message="t('pages.settings.infoDesc')" />
                      </a-col>
                    </a-row>
                  </a-card>
                </a-col>

                <!-- Tabs -->
                <a-col :span="24">
                  <a-tabs :active-key="activeTabKey" :class="{ 'icons-only': isMobile }" @change="onTabChange">
                    <a-tab-pane key="tpl-basic" class="tab-pane">
                      <template #tab>
                        <a-tooltip :title="isMobile ? t('pages.xray.basicTemplate') : null">
                          <SettingOutlined />
                        </a-tooltip>
                        <span v-if="!isMobile">{{ t('pages.xray.basicTemplate') }}</span>
                      </template>
                      <BasicsTab :template-settings="templateSettings" :outbound-test-url="outboundTestUrl"
                        :warp-exist="warpExist" :nord-exist="nordExist" :all-setting="allSetting"
                        @update:outbound-test-url="(v) => (outboundTestUrl = v)" @show-warp="showWarp"
                        @show-nord="showNord" @reset-default="resetToDefault" />
                    </a-tab-pane>

                    <a-tab-pane key="tpl-routing" class="tab-pane">
                      <template #tab>
                        <a-tooltip :title="isMobile ? t('pages.xray.Routings') : null">
                          <SwapOutlined />
                        </a-tooltip>
                        <span v-if="!isMobile">{{ t('pages.xray.Routings') }}</span>
                      </template>
                      <RoutingTab :template-settings="templateSettings" :inbound-tags="inboundTags"
                        :client-reverse-tags="clientReverseTags" :is-mobile="isMobile" />
                    </a-tab-pane>

                    <a-tab-pane key="tpl-outbound" class="tab-pane">
                      <template #tab>
                        <a-tooltip :title="isMobile ? t('pages.xray.Outbounds') : null">
                          <UploadOutlined />
                        </a-tooltip>
                        <span v-if="!isMobile">{{ t('pages.xray.Outbounds') }}</span>
                      </template>
                      <OutboundsTab :template-settings="templateSettings" :outbounds-traffic="outboundsTraffic"
                        :outbound-test-states="outboundTestStates" :testing-all="testingAll"
                        :inbound-tags="inboundTags" :is-mobile="isMobile"
                        @reset-traffic="resetOutboundsTraffic" @test="onTestOutbound"
                        @test-all="onTestAllOutbounds" @delete="onDeleteOutbound"
                        @show-warp="showWarp" @show-nord="showNord" />
                    </a-tab-pane>

                    <a-tab-pane key="tpl-balancer" class="tab-pane">
                      <template #tab>
                        <a-tooltip :title="isMobile ? t('pages.xray.Balancers') : null">
                          <ClusterOutlined />
                        </a-tooltip>
                        <span v-if="!isMobile">{{ t('pages.xray.Balancers') }}</span>
                      </template>
                      <BalancersTab :template-settings="templateSettings" 
                      :client-reverse-tags="clientReverseTags" :is-mobile="isMobile" />
                    </a-tab-pane>

                    <a-tab-pane key="tpl-dns" class="tab-pane">
                      <template #tab>
                        <a-tooltip :title="isMobile ? 'DNS' : null">
                          <DatabaseOutlined />
                        </a-tooltip>
                        <span v-if="!isMobile">DNS</span>
                      </template>
                      <DnsTab :template-settings="templateSettings" />
                    </a-tab-pane>

                    <a-tab-pane key="tpl-advanced" class="tab-pane">
                      <template #tab>
                        <a-tooltip :title="isMobile ? t('pages.xray.advancedTemplate') : null">
                          <CodeOutlined />
                        </a-tooltip>
                        <span v-if="!isMobile">{{ t('pages.xray.advancedTemplate') }}</span>
                      </template>
                      <a-list-item-meta :title="t('pages.xray.Template')" :description="t('pages.xray.TemplateDesc')" />
                      <a-radio-group v-model:value="advSettings" button-style="solid"
                        :size="isMobile ? 'small' : 'middle'" :style="{ margin: '12px 0' }">
                        <a-radio-button value="xraySetting">{{ t('pages.xray.completeTemplate') }}</a-radio-button>
                        <a-radio-button value="inboundSettings">{{ t('pages.xray.Inbounds') }}</a-radio-button>
                        <a-radio-button value="outboundSettings">{{ t('pages.xray.Outbounds') }}</a-radio-button>
                        <a-radio-button value="routingRuleSettings">{{ t('pages.xray.Routings') }}</a-radio-button>
                      </a-radio-group>
                      <JsonEditor v-model:value="advancedText" min-height="420px" max-height="720px" />
                    </a-tab-pane>
                  </a-tabs>
                </a-col>
              </a-row>
            </template>
          </a-spin>
        </a-layout-content>
      </a-layout>

      <WarpModal v-model:open="warpOpen" :template-settings="templateSettings" @add-outbound="onAddOutbound"
        @reset-outbound="onResetOutbound" @remove-outbound="onRemoveOutboundByTag" />
      <NordModal v-model:open="nordOpen" :template-settings="templateSettings" @add-outbound="onAddOutbound"
        @reset-outbound="onResetOutbound" @remove-outbound="onRemoveOutboundByIndex"
        @remove-routing-rules="onRemoveRoutingRules" />
    </a-layout>
  </a-config-provider>
</template>

<style scoped>
.xray-page {
  --bg-page: #e6e8ec;
  --bg-card: #ffffff;

  min-height: 100vh;
  background: var(--bg-page);
}

.xray-page.is-dark {
  --bg-page: #1e1e1e;
  --bg-card: #252526;
}

.xray-page.is-dark.is-ultra {
  --bg-page: #050505;
  --bg-card: #0c0e12;
}

.xray-page :deep(.ant-layout),
.xray-page :deep(.ant-layout-content) {
  background: transparent;
}

.content-shell {
  background: transparent;
}

.content-area {
  padding: 24px;
}

.loading-spacer {
  min-height: calc(100vh - 120px);
}

.header-row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
}

.header-actions {
  padding: 4px;
}

.header-info {
  display: flex;
  justify-content: flex-end;
}

.tab-pane {
  padding-top: 20px;
}

.restart-icon {
  font-size: 16px;
  cursor: pointer;
  color: var(--ant-primary-color, #1890ff);
}

.restart-result {
  max-width: 480px;
  white-space: pre-wrap;
  font-size: 12px;
  margin: 0;
}

.icons-only :deep(.ant-tabs-nav) {
  margin-bottom: 8px;
}

.icons-only :deep(.ant-tabs-nav-wrap) {
  width: 100%;
}

.icons-only :deep(.ant-tabs-nav-list) {
  display: flex;
  width: 100%;
}

.icons-only :deep(.ant-tabs-tab) {
  flex: 1 1 0;
  justify-content: center;
  margin: 0;
  padding: 10px 0;
}

.icons-only :deep(.ant-tabs-tab .anticon) {
  margin: 0;
  font-size: 18px;
}

.icons-only :deep(.ant-tabs-nav-operations) {
  display: none;
}
</style>
