// frontend/src/pages/settings/GeneralTab.tsx
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Collapse,
  Input,
  InputNumber,
  Select,
  Space,
  Switch,
} from 'antd';
import type { AllSetting } from '@/models/setting';
import { HttpUtil, LanguageManager } from '@/utils';
import SettingListItem from '@/components/SettingListItem';

interface ApiMsg<T = unknown> {
  success?: boolean;
  obj?: T;
}

interface GeneralTabProps {
  allSetting: AllSetting;
  updateSetting: (patch: Partial<AllSetting>) => void;
}

const REMARK_MODELS: Record<string, string> = { i: 'Inbound', e: 'Email', o: 'Other' };
const REMARK_SEPARATORS = [' ', '-', '_', '@', ':', '~', '|', ',', '.', '/'];
const TIMEZONES: string[] = [
  'Local',
  'UTC', 'GMT',
  'America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles',
  'America/Anchorage', 'Pacific/Honolulu',
  'America/Toronto', 'America/Vancouver', 'America/Mexico_City',
  'America/Sao_Paulo', 'America/Argentina/Buenos_Aires',
  'Europe/London', 'Europe/Paris', 'Europe/Berlin', 'Europe/Madrid',
  'Europe/Rome', 'Europe/Amsterdam', 'Europe/Stockholm', 'Europe/Zurich',
  'Europe/Moscow', 'Europe/Kyiv', 'Europe/Istanbul',
  'Asia/Tehran', 'Asia/Dubai', 'Asia/Kolkata', 'Asia/Dhaka',
  'Asia/Bangkok', 'Asia/Singapore', 'Asia/Shanghai', 'Asia/Tokyo',
  'Asia/Seoul', 'Asia/Hong_Kong', 'Asia/Taipei',
  'Australia/Sydney', 'Australia/Melbourne', 'Pacific/Auckland',
  'Africa/Cairo', 'Africa/Lagos', 'Africa/Johannesburg',
];

const DATEPICKER_LIST: { name: string; value: 'gregorian' | 'jalalian' }[] = [
  { name: 'Gregorian (Standard)', value: 'gregorian' },
  { name: 'Jalalian (شمسی)', value: 'jalalian' },
];

export default function GeneralTab({ allSetting, updateSetting }: GeneralTabProps) {
  const { t } = useTranslation();

  const [lang, setLang] = useState<string>(() => LanguageManager.getLanguage());
  const [inboundOptions, setInboundOptions] = useState<{ label: string; value: string }[]>([]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      // /options is the slim picker-shaped endpoint — it skips the heavy
      // per-client settings and clientStats payloads that /list ships.
      const msg = await HttpUtil.get('/panel/api/inbounds/options') as ApiMsg<{
        tag: string; protocol: string; port: number;
      }[]>;
      if (cancelled) return;
      if (msg?.success && Array.isArray(msg.obj)) {
        setInboundOptions(msg.obj.map((ib) => ({
          label: `${ib.tag} (${ib.protocol}@${ib.port})`,
          value: ib.tag,
        })));
      } else {
        setInboundOptions([]);
      }
    })();
    return () => { cancelled = true; };
  }, []);

  const remarkModel = useMemo(() => {
    const rm = allSetting.remarkModel || '';
    return rm.length > 1 ? rm.substring(1).split('') : [];
  }, [allSetting.remarkModel]);

  const remarkSeparator = useMemo(() => {
    const rm = allSetting.remarkModel || '-';
    return rm.length > 1 ? rm.charAt(0) : '-';
  }, [allSetting.remarkModel]);

  const remarkSample = useMemo(() => {
    const parts = remarkModel.map((k) => REMARK_MODELS[k]);
    return parts.length === 0 ? '' : parts.join(remarkSeparator);
  }, [remarkModel, remarkSeparator]);

  function setRemarkModel(parts: string[]) {
    updateSetting({ remarkModel: remarkSeparator + parts.join('') });
  }

  function setRemarkSeparator(sep: string) {
    const tail = (allSetting.remarkModel || '-').substring(1);
    updateSetting({ remarkModel: sep + tail });
  }

  const ldapInboundTagList = useMemo(() => {
    const csv = allSetting.ldapInboundTags || '';
    return csv.length ? csv.split(',').map((s) => s.trim()).filter(Boolean) : [];
  }, [allSetting.ldapInboundTags]);

  function setLdapInboundTagList(list: string[]) {
    updateSetting({ ldapInboundTags: Array.isArray(list) ? list.join(',') : '' });
  }

  function onLangChange(value: string) {
    setLang(value);
    LanguageManager.setLanguage(value);
  }

  const langOptions = useMemo(
    () => LanguageManager.supportedLanguages.map((l: { value: string; name: string; icon: string }) => ({
      value: l.value,
      label: (
        <>
          <span role="img" aria-label={l.name}>{l.icon}</span>
          &nbsp;&nbsp;<span>{l.name}</span>
        </>
      ),
    })),
    [],
  );

  return (
    <Collapse defaultActiveKey="1" items={[
      {
        key: '1',
        label: t('pages.settings.panelSettings'),
        children: (
          <>
            <SettingListItem
              paddings="small"
              title={t('pages.settings.remarkModel')}
              description={<>{t('pages.settings.sampleRemark')}: <i>#{remarkSample}</i></>}
            >
              <Space.Compact style={{ width: '100%' }}>
                <Select
                  mode="multiple"
                  value={remarkModel}
                  onChange={setRemarkModel}
                  style={{ paddingRight: '.5rem', minWidth: '80%', width: 'auto' }}
                  options={Object.entries(REMARK_MODELS).map(([k, l]) => ({ value: k, label: l }))}
                />
                <Select
                  value={remarkSeparator}
                  onChange={setRemarkSeparator}
                  style={{ width: '20%' }}
                  options={REMARK_SEPARATORS.map((s) => ({ value: s, label: s }))}
                />
              </Space.Compact>
            </SettingListItem>

            <SettingListItem paddings="small" title={t('pages.settings.panelListeningIP')} description={t('pages.settings.panelListeningIPDesc')}>
              <Input value={allSetting.webListen} onChange={(e) => updateSetting({ webListen: e.target.value })} />
            </SettingListItem>

            <SettingListItem paddings="small" title={t('pages.settings.panelListeningDomain')} description={t('pages.settings.panelListeningDomainDesc')}>
              <Input value={allSetting.webDomain} onChange={(e) => updateSetting({ webDomain: e.target.value })} />
            </SettingListItem>

            <SettingListItem paddings="small" title={t('pages.settings.panelPort')} description={t('pages.settings.panelPortDesc')}>
              <InputNumber value={allSetting.webPort} min={1} max={65535} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ webPort: Number(v) || 0 })} />
            </SettingListItem>

            <SettingListItem paddings="small" title={t('pages.settings.panelUrlPath')} description={t('pages.settings.panelUrlPathDesc')}>
              <Input value={allSetting.webBasePath} onChange={(e) => updateSetting({ webBasePath: e.target.value })} />
            </SettingListItem>

            <SettingListItem paddings="small" title={t('pages.settings.sessionMaxAge')} description={t('pages.settings.sessionMaxAgeDesc')}>
              <InputNumber value={allSetting.sessionMaxAge} min={60} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ sessionMaxAge: Number(v) || 0 })} />
            </SettingListItem>

            <SettingListItem
              paddings="small"
              title={t('pages.settings.trustedProxyCIDRs')}
              description={t('pages.settings.trustedProxyCIDRsDesc')}
            >
              <Input
                value={allSetting.trustedProxyCIDRs}
                placeholder="127.0.0.1/32,::1/128"
                onChange={(e) => updateSetting({ trustedProxyCIDRs: e.target.value })}
              />
            </SettingListItem>

            <SettingListItem paddings="small" title={t('pages.settings.pageSize')} description={t('pages.settings.pageSizeDesc')}>
              <InputNumber value={allSetting.pageSize} min={0} step={5} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ pageSize: Number(v) || 0 })} />
            </SettingListItem>

            <SettingListItem paddings="small" title={t('pages.settings.language')}>
              <Select
                value={lang}
                onChange={onLangChange}
                style={{ width: '100%' }}
                options={langOptions}
              />
            </SettingListItem>
          </>
        ),
      },
      {
        key: '2',
        label: t('pages.settings.notifications'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.expireTimeDiff')} description={t('pages.settings.expireTimeDiffDesc')}>
              <InputNumber value={allSetting.expireDiff} min={0} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ expireDiff: Number(v) || 0 })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.trafficDiff')} description={t('pages.settings.trafficDiffDesc')}>
              <InputNumber value={allSetting.trafficDiff} min={0} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ trafficDiff: Number(v) || 0 })} />
            </SettingListItem>
          </>
        ),
      },
      {
        key: '3',
        label: t('pages.settings.certs'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.publicKeyPath')} description={t('pages.settings.publicKeyPathDesc')}>
              <Input value={allSetting.webCertFile} onChange={(e) => updateSetting({ webCertFile: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.privateKeyPath')} description={t('pages.settings.privateKeyPathDesc')}>
              <Input value={allSetting.webKeyFile} onChange={(e) => updateSetting({ webKeyFile: e.target.value })} />
            </SettingListItem>
          </>
        ),
      },
      {
        key: '4',
        label: t('pages.settings.externalTraffic'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.externalTrafficInformEnable')} description={t('pages.settings.externalTrafficInformEnableDesc')}>
              <Switch checked={allSetting.externalTrafficInformEnable}
                onChange={(v) => updateSetting({ externalTrafficInformEnable: v })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.externalTrafficInformURI')} description={t('pages.settings.externalTrafficInformURIDesc')}>
              <Input
                value={allSetting.externalTrafficInformURI}
                placeholder="(http|https)://domain[:port]/path/"
                onChange={(e) => updateSetting({ externalTrafficInformURI: e.target.value })}
              />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.restartXrayOnClientDisable')} description={t('pages.settings.restartXrayOnClientDisableDesc')}>
              <Switch checked={allSetting.restartXrayOnClientDisable}
                onChange={(v) => updateSetting({ restartXrayOnClientDisable: v })} />
            </SettingListItem>
          </>
        ),
      },
      {
        key: '5',
        label: t('pages.settings.dateAndTime'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.timeZone')} description={t('pages.settings.timeZoneDesc')}>
              <Select
                showSearch
                value={allSetting.timeLocation || 'Local'}
                onChange={(v) => updateSetting({ timeLocation: v })}
                style={{ width: '100%' }}
                options={TIMEZONES.map((tz) => ({ value: tz, label: tz }))}
                filterOption={(input, option) =>
                  (option?.label as string)?.toLowerCase().includes(input.toLowerCase())
                }
              />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.datepicker')} description={t('pages.settings.datepickerDescription')}>
              <Select
                value={allSetting.datepicker || 'gregorian'}
                onChange={(v) => updateSetting({ datepicker: v as 'gregorian' | 'jalalian' })}
                style={{ width: '100%' }}
                options={DATEPICKER_LIST.map((d) => ({ value: d.value, label: d.name }))}
              />
            </SettingListItem>
          </>
        ),
      },
      {
        key: '6',
        label: t('pages.settings.ldap.title'),
        children: (
          <>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.enable')}>
              <Switch checked={allSetting.ldapEnable} onChange={(v) => updateSetting({ ldapEnable: v })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.host')}>
              <Input value={allSetting.ldapHost} onChange={(e) => updateSetting({ ldapHost: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.port')}>
              <InputNumber value={allSetting.ldapPort} min={1} max={65535} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ ldapPort: Number(v) || 0 })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.useTLS')}>
              <Switch checked={allSetting.ldapUseTLS} onChange={(v) => updateSetting({ ldapUseTLS: v })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.bindDN')}>
              <Input value={allSetting.ldapBindDN} onChange={(e) => updateSetting({ ldapBindDN: e.target.value })} />
            </SettingListItem>
            <SettingListItem
              paddings="small"
              title={t('password')}
              description={allSetting.hasLdapPassword ? t('pages.settings.ldap.passwordConfigured') : t('pages.settings.ldap.passwordNotConfigured')}
            >
              <Input.Password
                value={allSetting.ldapPassword}
                placeholder={allSetting.hasLdapPassword ? t('pages.settings.ldap.passwordPlaceholder') : ''}
                onChange={(e) => updateSetting({ ldapPassword: e.target.value })}
              />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.baseDN')}>
              <Input value={allSetting.ldapBaseDN} onChange={(e) => updateSetting({ ldapBaseDN: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.userFilter')}>
              <Input value={allSetting.ldapUserFilter} onChange={(e) => updateSetting({ ldapUserFilter: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.userAttr')}>
              <Input value={allSetting.ldapUserAttr} onChange={(e) => updateSetting({ ldapUserAttr: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.vlessField')}>
              <Input value={allSetting.ldapVlessField} onChange={(e) => updateSetting({ ldapVlessField: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.flagField')} description={t('pages.settings.ldap.flagFieldDesc')}>
              <Input value={allSetting.ldapFlagField} onChange={(e) => updateSetting({ ldapFlagField: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.truthyValues')} description={t('pages.settings.ldap.truthyValuesDesc')}>
              <Input value={allSetting.ldapTruthyValues} onChange={(e) => updateSetting({ ldapTruthyValues: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.invertFlag')} description={t('pages.settings.ldap.invertFlagDesc')}>
              <Switch checked={allSetting.ldapInvertFlag} onChange={(v) => updateSetting({ ldapInvertFlag: v })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.syncCron')} description={t('pages.settings.ldap.syncCronDesc')}>
              <Input value={allSetting.ldapSyncCron} onChange={(e) => updateSetting({ ldapSyncCron: e.target.value })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.inboundTags')} description={t('pages.settings.ldap.inboundTagsDesc')}>
              <>
                <Select
                  mode="multiple"
                  value={ldapInboundTagList}
                  onChange={setLdapInboundTagList}
                  style={{ width: '100%' }}
                  options={inboundOptions}
                />
                {inboundOptions.length === 0 && (
                  <div className="ldap-no-inbounds">{t('pages.settings.ldap.noInbounds')}</div>
                )}
              </>
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.autoCreate')}>
              <Switch checked={allSetting.ldapAutoCreate} onChange={(v) => updateSetting({ ldapAutoCreate: v })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.autoDelete')}>
              <Switch checked={allSetting.ldapAutoDelete} onChange={(v) => updateSetting({ ldapAutoDelete: v })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.defaultTotalGB')}>
              <InputNumber value={allSetting.ldapDefaultTotalGB} min={0} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ ldapDefaultTotalGB: Number(v) || 0 })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.defaultExpiryDays')}>
              <InputNumber value={allSetting.ldapDefaultExpiryDays} min={0} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ ldapDefaultExpiryDays: Number(v) || 0 })} />
            </SettingListItem>
            <SettingListItem paddings="small" title={t('pages.settings.ldap.defaultLimitIP')}>
              <InputNumber value={allSetting.ldapDefaultLimitIP} min={0} style={{ width: '100%' }}
                onChange={(v) => updateSetting({ ldapDefaultLimitIP: Number(v) || 0 })} />
            </SettingListItem>
          </>
        ),
      },
    ]} />
  );
}

// frontend/src/pages/settings/GeneralTab.vue
<script setup>
import { computed, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { HttpUtil, LanguageManager } from '@/utils';
import SettingListItem from '@/components/SettingListItem.vue';

const { t } = useI18n();

function getTimezones() {
  try {
    return Intl.supportedValuesOf('timeZone');
  } catch {
    return ['UTC', 'Asia/Shanghai', 'Asia/Tokyo', 'Asia/Seoul', 'Asia/Singapore',
      'America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles',
      'Europe/London', 'Europe/Paris', 'Europe/Berlin', 'Europe/Moscow'];
  }
}

function getTzOffsetMinutes(tz) {
  try {
    const now = Date.now();
    const utcDate = new Date(new Intl.DateTimeFormat('en-US', {
      timeZone: 'UTC', year: 'numeric', month: 'numeric', day: 'numeric',
      hour: 'numeric', minute: 'numeric', second: 'numeric',
    }).format(now));
    const tzDate = new Date(new Intl.DateTimeFormat('en-US', {
      timeZone: tz, year: 'numeric', month: 'numeric', day: 'numeric',
      hour: 'numeric', minute: 'numeric', second: 'numeric',
    }).format(now));
    return (tzDate - utcDate) / 60000;
  } catch {
    return 0;
  }
}

function formatTzOffset(minutes) {
  const sign = minutes >= 0 ? '+' : '-';
  const totalHours = Math.abs(minutes) / 60;
  if (totalHours % 1 === 0) return `UTC${sign}${Math.floor(totalHours)}`;
  return `UTC${sign}${totalHours.toFixed(2).replace(/0+$/, '').replace(/\.$/, '')}`;
}

function getMachineTimezone() {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone;
  } catch {
    return 'Asia/Shanghai';
  }
}

const timezoneOptions = ref([]);

onMounted(() => {
  const zones = getTimezones();
  const mapped = zones.map(z => {
    const offsetMin = getTzOffsetMinutes(z);
    return {
      label: `${z.replace(/_/g, ' ')} (${formatTzOffset(offsetMin)})`,
      value: z,
      offsetMin,
    };
  });
  mapped.sort((a, b) => a.offsetMin - b.offsetMin || a.value.localeCompare(b.value));
  timezoneOptions.value = mapped;

  // If timeLocation is "Local" (Go's default), replace with browser's actual timezone
  if (props.allSetting?.timeLocation === 'Local') {
    const machineTz = getMachineTimezone();
    if (machineTz) props.allSetting.timeLocation = machineTz;
  }
});

const props = defineProps({
  // Reactive AllSetting instance shared with the parent page.
  allSetting: { type: Object, required: true },
});

// Remark model — legacy stores it as a single string where index 0 is
// the separator char and the rest is the order of model keys
// (i=Inbound, e=Email, o=Other). Surface it as two v-models that read
// and write the underlying string.
const remarkModels = { i: 'Inbound', e: 'Email', o: 'Other' };
const remarkSeparators = [' ', '-', '_', '@', ':', '~', '|', ',', '.', '/'];

const remarkModel = computed({
  get: () => {
    const rm = props.allSetting.remarkModel || '';
    return rm.length > 1 ? rm.substring(1).split('') : [];
  },
  set: (value) => {
    const sep = (props.allSetting.remarkModel || '-').charAt(0);
    props.allSetting.remarkModel = sep + value.join('');
  },
});

const remarkSeparator = computed({
  get: () => {
    const rm = props.allSetting.remarkModel || '-';
    return rm.length > 1 ? rm.charAt(0) : '-';
  },
  set: (value) => {
    const tail = (props.allSetting.remarkModel || '-').substring(1);
    props.allSetting.remarkModel = value + tail;
  },
});

const remarkSample = computed(() => {
  const parts = remarkModel.value.map((k) => remarkModels[k]);
  return parts.length === 0 ? '' : parts.join(remarkSeparator.value);
});

const datepicker = computed({
  get: () => props.allSetting.datepicker || 'gregorian',
  set: (value) => { props.allSetting.datepicker = value; },
});

const datepickerList = computed(() => [
  { name: t('pages.settings.gregorian') || 'Gregorian (Standard)', value: 'gregorian' },
  { name: t('pages.settings.jalalian') || 'Jalalian (شمسی)', value: 'jalalian' },
]);

// Language is stored client-side in a cookie, NOT in AllSetting. The
// legacy panel reloads on change so the Go side renders templates in
// the new language.
const lang = ref(LanguageManager.getLanguage());
function onLangChange() {
  LanguageManager.setLanguage(lang.value);
}

// LDAP inbound tags are CSV on the wire; expose as an array so the
// multi-select v-model works directly.
const ldapInboundTagList = computed({
  get: () => {
    const csv = props.allSetting.ldapInboundTags || '';
    return csv.length ? csv.split(',').map((s) => s.trim()).filter(Boolean) : [];
  },
  set: (list) => {
    props.allSetting.ldapInboundTags = Array.isArray(list) ? list.join(',') : '';
  },
});

const inboundOptions = ref([]);
async function loadInboundTags() {
  const msg = await HttpUtil.get('/panel/api/inbounds/list');
  if (msg?.success && Array.isArray(msg.obj)) {
    inboundOptions.value = msg.obj.map((ib) => ({
      label: `${ib.tag} (${ib.protocol}@${ib.port})`,
      value: ib.tag,
    }));
  } else {
    inboundOptions.value = [];
  }
}

onMounted(loadInboundTags);
</script>

<template>
  <a-collapse default-active-key="1">
    <a-collapse-panel key="1" :header="t('pages.settings.panelSettings')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.remarkModel') }}</template>
        <template #description>{{ t('pages.settings.sampleRemark') }}: <i>#{{ remarkSample }}</i></template>
        <template #control>
          <a-input-group :style="{ width: '100%' }">
            <a-select v-model:value="remarkModel" mode="multiple"
              :style="{ paddingRight: '.5rem', minWidth: '80%', width: 'auto' }">
              <a-select-option v-for="(label, key) in remarkModels" :key="key" :value="key">
                {{ label }}
              </a-select-option>
            </a-select>
            <a-select v-model:value="remarkSeparator" :style="{ width: '20%' }">
              <a-select-option v-for="sep in remarkSeparators" :key="sep" :value="sep">{{ sep }}</a-select-option>
            </a-select>
          </a-input-group>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.panelListeningIP') }}</template>
        <template #description>{{ t('pages.settings.panelListeningIPDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.webListen" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.panelListeningDomain') }}</template>
        <template #description>{{ t('pages.settings.panelListeningDomainDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.webDomain" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.panelPort') }}</template>
        <template #description>{{ t('pages.settings.panelPortDesc') }}</template>
        <template #control>
          <a-input-number v-model:value="allSetting.webPort" :min="1" :max="65535" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.panelUrlPath') }}</template>
        <template #description>{{ t('pages.settings.panelUrlPathDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.webBasePath" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.sessionMaxAge') }}</template>
        <template #description>{{ t('pages.settings.sessionMaxAgeDesc') }}</template>
        <template #control>
          <a-input-number v-model:value="allSetting.sessionMaxAge" :min="60" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Trusted proxy CIDRs</template>
        <template #description>Comma-separated IPs/CIDRs allowed to set forwarded host, proto, and client IP headers.</template>
        <template #control>
          <a-input v-model:value="allSetting.trustedProxyCIDRs" placeholder="127.0.0.1/32,::1/128" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.pageSize') }}</template>
        <template #description>{{ t('pages.settings.pageSizeDesc') }}</template>
        <template #control>
          <a-input-number v-model:value="allSetting.pageSize" :min="0" :step="5" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.language') }}</template>
        <template #control>
          <a-select v-model:value="lang" :style="{ width: '100%' }" @change="onLangChange">
            <a-select-option v-for="l in LanguageManager.supportedLanguages" :key="l.value" :value="l.value"
              :label="l.value">
              <span role="img" :aria-label="l.name">{{ l.icon }}</span>
              &nbsp;&nbsp;<span>{{ l.name }}</span>
            </a-select-option>
          </a-select>
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="2" :header="t('pages.settings.notifications')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.expireTimeDiff') }}</template>
        <template #description>{{ t('pages.settings.expireTimeDiffDesc') }}</template>
        <template #control>
          <a-input-number v-model:value="allSetting.expireDiff" :min="0" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.trafficDiff') }}</template>
        <template #description>{{ t('pages.settings.trafficDiffDesc') }}</template>
        <template #control>
          <a-input-number v-model:value="allSetting.trafficDiff" :min="0" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="3" :header="t('pages.settings.certs')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.publicKeyPath') }}</template>
        <template #description>{{ t('pages.settings.publicKeyPathDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.webCertFile" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.privateKeyPath') }}</template>
        <template #description>{{ t('pages.settings.privateKeyPathDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.webKeyFile" type="text" />
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="4" :header="t('pages.settings.externalTraffic')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.externalTrafficInformEnable') }}</template>
        <template #description>{{ t('pages.settings.externalTrafficInformEnableDesc') }}</template>
        <template #control>
          <a-switch v-model:checked="allSetting.externalTrafficInformEnable" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.externalTrafficInformURI') }}</template>
        <template #description>{{ t('pages.settings.externalTrafficInformURIDesc') }}</template>
        <template #control>
          <a-input v-model:value="allSetting.externalTrafficInformURI" placeholder="(http|https)://domain[:port]/path/"
            type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.restartXrayOnClientDisable') }}</template>
        <template #description>{{ t('pages.settings.restartXrayOnClientDisableDesc') }}</template>
        <template #control>
          <a-switch v-model:checked="allSetting.restartXrayOnClientDisable" />
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="5" :header="t('pages.settings.dateAndTime')">
      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.timeZone') }}</template>
        <template #description>{{ t('pages.settings.timeZoneDesc') }}</template>
        <template #control>
          <a-select v-model:value="allSetting.timeLocation" show-search
            :filter-option="(input, option) => option.value.toLowerCase().includes(input.toLowerCase())"
            :style="{ width: '100%' }">
            <a-select-option v-for="tz in timezoneOptions" :key="tz.value" :value="tz.value">
              {{ tz.label }}
            </a-select-option>
          </a-select>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('pages.settings.datepicker') }}</template>
        <template #description>{{ t('pages.settings.datepickerDescription') }}</template>
        <template #control>
          <a-select v-model:value="datepicker" :style="{ width: '100%' }">
            <a-select-option v-for="item in datepickerList" :key="item.value" :value="item.value">
              {{ item.name }}
            </a-select-option>
          </a-select>
        </template>
      </SettingListItem>
    </a-collapse-panel>

    <a-collapse-panel key="6" header="LDAP">
      <SettingListItem paddings="small">
        <template #title>Enable LDAP sync</template>
        <template #control>
          <a-switch v-model:checked="allSetting.ldapEnable" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>LDAP host</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapHost" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>LDAP port</template>
        <template #control>
          <a-input-number v-model:value="allSetting.ldapPort" :min="1" :max="65535" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Use TLS (LDAPS)</template>
        <template #control>
          <a-switch v-model:checked="allSetting.ldapUseTLS" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Bind DN</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapBindDN" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>{{ t('password') }}</template>
        <template #description>
          {{ allSetting.hasLdapPassword ? 'Configured; leave blank to keep current password.' : 'Not configured.' }}
        </template>
        <template #control>
          <a-input-password v-model:value="allSetting.ldapPassword"
            :placeholder="allSetting.hasLdapPassword ? 'Configured - enter a new value to replace' : ''" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Base DN</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapBaseDN" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>User filter</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapUserFilter" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>User attribute (username/email)</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapUserAttr" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>VLESS flag attribute</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapVlessField" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Generic flag attribute (optional)</template>
        <template #description>If set, overrides VLESS flag — e.g. shadowInactive.</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapFlagField" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Truthy values</template>
        <template #description>Comma-separated; default: true,1,yes,on</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapTruthyValues" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Invert flag</template>
        <template #description>Enable when the attribute means disabled (e.g. shadowInactive).</template>
        <template #control>
          <a-switch v-model:checked="allSetting.ldapInvertFlag" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Sync schedule</template>
        <template #description>Cron-like string, e.g. @every 1m</template>
        <template #control>
          <a-input v-model:value="allSetting.ldapSyncCron" type="text" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Inbound tags</template>
        <template #description>Inbounds that LDAP sync may auto-create or auto-delete clients on.</template>
        <template #control>
          <a-select v-model:value="ldapInboundTagList" mode="multiple" :style="{ width: '100%' }">
            <a-select-option v-for="opt in inboundOptions" :key="opt.value" :value="opt.value">
              {{ opt.label }}
            </a-select-option>
          </a-select>
          <div v-if="inboundOptions.length === 0" class="ldap-no-inbounds">
            No inbounds found. Create one in Inbounds first.
          </div>
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Auto create clients</template>
        <template #control>
          <a-switch v-model:checked="allSetting.ldapAutoCreate" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Auto delete clients</template>
        <template #control>
          <a-switch v-model:checked="allSetting.ldapAutoDelete" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Default total (GB)</template>
        <template #control>
          <a-input-number v-model:value="allSetting.ldapDefaultTotalGB" :min="0" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Default expiry (days)</template>
        <template #control>
          <a-input-number v-model:value="allSetting.ldapDefaultExpiryDays" :min="0" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>

      <SettingListItem paddings="small">
        <template #title>Default IP limit</template>
        <template #control>
          <a-input-number v-model:value="allSetting.ldapDefaultLimitIP" :min="0" :style="{ width: '100%' }" />
        </template>
      </SettingListItem>
    </a-collapse-panel>
  </a-collapse>
</template>

<style scoped>
.ldap-no-inbounds {
  margin-top: 6px;
  color: #999;
  font-size: 12px;
}
</style>
